trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: solution
    value: 'MagicalYatzyXF.sln'
  - name: project
    value: 'MagicalYatzyXF/MagicalYatzyXF.GTK/MagicalYatzyXF.GTK.csproj'
  - name: buildPlatform
    value: 'AnyCPU'
  - name: buildConfiguration
    value: 'Debug'

steps:

- task: UseDotNet@2
  displayName: 'Use dotnet sdk 3.x'
  inputs:
    version: 3.x
    includePreviewVersions: false

- task: NuGetToolInstaller@1
  displayName: 'Install nuget'

- task: NuGetCommand@2
  displayName: 'Restore nuget packages'
  inputs:
    restoreSolution: '$(solution)'

- task: Bash@3
  displayName: 'Update Mono version'
  inputs:
    targetType: 'inline'
    script: |
      SYMLINK=6_4_0
      MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
      echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
      echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
      echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"

- task: MSBuild@1
  inputs:
    solution: '$(project)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'