//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.60310.0
// 

using System.Runtime.Serialization;

namespace Sanet.MagicalYatzy.Dto.ConnectedServices.LegacyScoreService {
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="KniffelScore", Namespace="http://www.sanet.com/")]
    public partial class KniffelScore : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int HighScoreField;
        
        private int IdField;
        
        private int TotalField;
        
        private int GamesField;
        
        private string PlayerField;
        
        private string PassField;
        
        private string PicUrlField;
        
        private string TableField;
        
        private int PlaceField;
        
        [DataMember(IsRequired=true)]
        public int HighScore {
            get {
                return this.HighScoreField;
            }
            set {
                if ((this.HighScoreField.Equals(value) != true)) {
                    this.HighScoreField = value;
                    this.RaisePropertyChanged("HighScore");
                }
            }
        }
        
        [DataMember(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [DataMember(IsRequired=true)]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [DataMember(IsRequired=true, Order=3)]
        public int Games {
            get {
                return this.GamesField;
            }
            set {
                if ((this.GamesField.Equals(value) != true)) {
                    this.GamesField = value;
                    this.RaisePropertyChanged("Games");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public string Player {
            get {
                return this.PlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerField, value) != true)) {
                    this.PlayerField = value;
                    this.RaisePropertyChanged("Player");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=5)]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=6)]
        public string PicUrl {
            get {
                return this.PicUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PicUrlField, value) != true)) {
                    this.PicUrlField = value;
                    this.RaisePropertyChanged("PicUrl");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=7)]
        public string Table {
            get {
                return this.TableField;
            }
            set {
                if ((object.ReferenceEquals(this.TableField, value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
        
        [DataMember(IsRequired=true, Order=8)]
        public int Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((this.PlaceField.Equals(value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sanet.com/", ConfigurationName="KniffelLeaderBoardService.KniffelServiceSoap")]
    public interface KniffelServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.sanet.com/PutScore", ReplyAction="*")]
        System.IAsyncResult BeginPutScore(PutScoreRequest request, System.AsyncCallback callback, object asyncState);
        
        PutScoreResponse EndPutScore(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.sanet.com/PutScoreIntoTable", ReplyAction="*")]
        System.IAsyncResult BeginPutScoreIntoTable(PutScoreIntoTableRequest request, System.AsyncCallback callback, object asyncState);
        
        PutScoreIntoTableResponse EndPutScoreIntoTable(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.sanet.com/PutScoreIntoTableWithPic", ReplyAction="*")]
        System.IAsyncResult BeginPutScoreIntoTableWithPic(PutScoreIntoTableWithPicRequest request, System.AsyncCallback callback, object asyncState);
        
        PutScoreIntoTableWithPicResponse EndPutScoreIntoTableWithPic(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.sanet.com/PutScoreIntoTableWithPicPureName", ReplyAction="*")]
        System.IAsyncResult BeginPutScoreIntoTableWithPicPureName(PutScoreIntoTableWithPicPureNameRequest request, System.AsyncCallback callback, object asyncState);
        
        PutScoreIntoTableWithPicPureNameResponse EndPutScoreIntoTableWithPicPureName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.sanet.com/PutOnlineServerLog", ReplyAction="*")]
        System.IAsyncResult BeginPutOnlineServerLog(PutOnlineServerLogRequest request, System.AsyncCallback callback, object asyncState);
        
        PutOnlineServerLogResponse EndPutOnlineServerLog(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.sanet.com/GetTopPlayers", ReplyAction="*")]
        System.IAsyncResult BeginGetTopPlayers(GetTopPlayersRequest request, System.AsyncCallback callback, object asyncState);
        
        GetTopPlayersResponse EndGetTopPlayers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.sanet.com/GetChempion", ReplyAction="*")]
        System.IAsyncResult BeginGetChempion(GetChempionRequest request, System.AsyncCallback callback, object asyncState);
        
        GetChempionResponse EndGetChempion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.sanet.com/GetLastWeekChempion", ReplyAction="*")]
        System.IAsyncResult BeginGetLastWeekChempion(GetLastWeekChempionRequest request, System.AsyncCallback callback, object asyncState);
        
        GetLastWeekChempionResponse EndGetLastWeekChempion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.sanet.com/GetLastDayChempion", ReplyAction="*")]
        System.IAsyncResult BeginGetLastDayChempion(GetLastDayChempionRequest request, System.AsyncCallback callback, object asyncState);
        
        GetLastDayChempionResponse EndGetLastDayChempion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.sanet.com/GetPlayersMagics", ReplyAction="*")]
        System.IAsyncResult BeginGetPlayersMagics(GetPlayersMagicsRequest request, System.AsyncCallback callback, object asyncState);
        
        GetPlayersMagicsResponse EndGetPlayersMagics(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.sanet.com/AddPlayersMagics", ReplyAction="*")]
        System.IAsyncResult BeginAddPlayersMagics(AddPlayersMagicsRequest request, System.AsyncCallback callback, object asyncState);
        
        AddPlayersMagicsResponse EndAddPlayersMagics(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScore", Namespace="http://www.sanet.com/", Order=0)]
        public PutScoreRequestBody Body;
        
        public PutScoreRequest() {
        }
        
        public PutScoreRequest(PutScoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class PutScoreRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public PutScoreRequestBody() {
        }
        
        public PutScoreRequestBody(string UserName, string Pass, string Score) {
            this.UserName = UserName;
            this.Pass = Pass;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreResponse", Namespace="http://www.sanet.com/", Order=0)]
        public PutScoreResponseBody Body;
        
        public PutScoreResponse() {
        }
        
        public PutScoreResponse(PutScoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class PutScoreResponseBody {
        
        [DataMember(Order=0)]
        public bool PutScoreResult;
        
        public PutScoreResponseBody() {
        }
        
        public PutScoreResponseBody(bool PutScoreResult) {
            this.PutScoreResult = PutScoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTable", Namespace="http://www.sanet.com/", Order=0)]
        public PutScoreIntoTableRequestBody Body;
        
        public PutScoreIntoTableRequest() {
        }
        
        public PutScoreIntoTableRequest(PutScoreIntoTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string table;
        
        public PutScoreIntoTableRequestBody() {
        }
        
        public PutScoreIntoTableRequestBody(string UserName, string Pass, string Score, string table) {
            this.UserName = UserName;
            this.Pass = Pass;
            this.Score = Score;
            this.table = table;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableResponse", Namespace="http://www.sanet.com/", Order=0)]
        public PutScoreIntoTableResponseBody Body;
        
        public PutScoreIntoTableResponse() {
        }
        
        public PutScoreIntoTableResponse(PutScoreIntoTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableResponseBody {
        
        [DataMember(Order=0)]
        public bool PutScoreIntoTableResult;
        
        public PutScoreIntoTableResponseBody() {
        }
        
        public PutScoreIntoTableResponseBody(bool PutScoreIntoTableResult) {
            this.PutScoreIntoTableResult = PutScoreIntoTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableWithPicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableWithPic", Namespace="http://www.sanet.com/", Order=0)]
        public PutScoreIntoTableWithPicRequestBody Body;
        
        public PutScoreIntoTableWithPicRequest() {
        }
        
        public PutScoreIntoTableWithPicRequest(PutScoreIntoTableWithPicRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableWithPicRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string table;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public string picurl;
        
        public PutScoreIntoTableWithPicRequestBody() {
        }
        
        public PutScoreIntoTableWithPicRequestBody(string UserName, string Pass, string Score, string table, string picurl) {
            this.UserName = UserName;
            this.Pass = Pass;
            this.Score = Score;
            this.table = table;
            this.picurl = picurl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableWithPicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableWithPicResponse", Namespace="http://www.sanet.com/", Order=0)]
        public PutScoreIntoTableWithPicResponseBody Body;
        
        public PutScoreIntoTableWithPicResponse() {
        }
        
        public PutScoreIntoTableWithPicResponse(PutScoreIntoTableWithPicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableWithPicResponseBody {
        
        [DataMember(Order=0)]
        public bool PutScoreIntoTableWithPicResult;
        
        public PutScoreIntoTableWithPicResponseBody() {
        }
        
        public PutScoreIntoTableWithPicResponseBody(bool PutScoreIntoTableWithPicResult) {
            this.PutScoreIntoTableWithPicResult = PutScoreIntoTableWithPicResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableWithPicPureNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableWithPicPureName", Namespace="http://www.sanet.com/", Order=0)]
        public PutScoreIntoTableWithPicPureNameRequestBody Body;
        
        public PutScoreIntoTableWithPicPureNameRequest() {
        }
        
        public PutScoreIntoTableWithPicPureNameRequest(PutScoreIntoTableWithPicPureNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableWithPicPureNameRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string table;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public string picurl;
        
        public PutScoreIntoTableWithPicPureNameRequestBody() {
        }
        
        public PutScoreIntoTableWithPicPureNameRequestBody(string UserName, string Pass, string Score, string table, string picurl) {
            this.UserName = UserName;
            this.Pass = Pass;
            this.Score = Score;
            this.table = table;
            this.picurl = picurl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableWithPicPureNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableWithPicPureNameResponse", Namespace="http://www.sanet.com/", Order=0)]
        public PutScoreIntoTableWithPicPureNameResponseBody Body;
        
        public PutScoreIntoTableWithPicPureNameResponse() {
        }
        
        public PutScoreIntoTableWithPicPureNameResponse(PutScoreIntoTableWithPicPureNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableWithPicPureNameResponseBody {
        
        [DataMember(Order=0)]
        public bool PutScoreIntoTableWithPicPureNameResult;
        
        public PutScoreIntoTableWithPicPureNameResponseBody() {
        }
        
        public PutScoreIntoTableWithPicPureNameResponseBody(bool PutScoreIntoTableWithPicPureNameResult) {
            this.PutScoreIntoTableWithPicPureNameResult = PutScoreIntoTableWithPicPureNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutOnlineServerLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutOnlineServerLog", Namespace="http://www.sanet.com/", Order=0)]
        public PutOnlineServerLogRequestBody Body;
        
        public PutOnlineServerLogRequest() {
        }
        
        public PutOnlineServerLogRequest(PutOnlineServerLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class PutOnlineServerLogRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string message;
        
        public PutOnlineServerLogRequestBody() {
        }
        
        public PutOnlineServerLogRequestBody(string source, string message) {
            this.source = source;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutOnlineServerLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutOnlineServerLogResponse", Namespace="http://www.sanet.com/", Order=0)]
        public PutOnlineServerLogResponseBody Body;
        
        public PutOnlineServerLogResponse() {
        }
        
        public PutOnlineServerLogResponse(PutOnlineServerLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract()]
    public partial class PutOnlineServerLogResponseBody {
        
        public PutOnlineServerLogResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopPlayersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopPlayers", Namespace="http://www.sanet.com/", Order=0)]
        public GetTopPlayersRequestBody Body;
        
        public GetTopPlayersRequest() {
        }
        
        public GetTopPlayersRequest(GetTopPlayersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class GetTopPlayersRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string rules;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public KniffelScore[] Players;
        
        public GetTopPlayersRequestBody() {
        }
        
        public GetTopPlayersRequestBody(string rules, KniffelScore[] Players) {
            this.rules = rules;
            this.Players = Players;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopPlayersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopPlayersResponse", Namespace="http://www.sanet.com/", Order=0)]
        public GetTopPlayersResponseBody Body;
        
        public GetTopPlayersResponse() {
        }
        
        public GetTopPlayersResponse(GetTopPlayersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class GetTopPlayersResponseBody {
        
        [DataMember(Order=0)]
        public bool GetTopPlayersResult;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public KniffelScore[] Players;
        
        public GetTopPlayersResponseBody() {
        }
        
        public GetTopPlayersResponseBody(bool GetTopPlayersResult, KniffelScore[] Players) {
            this.GetTopPlayersResult = GetTopPlayersResult;
            this.Players = Players;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChempionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChempion", Namespace="http://www.sanet.com/", Order=0)]
        public GetChempionRequestBody Body;
        
        public GetChempionRequest() {
        }
        
        public GetChempionRequest(GetChempionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class GetChempionRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string rules;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetChempionRequestBody() {
        }
        
        public GetChempionRequestBody(string rules, string Name, string Score) {
            this.rules = rules;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChempionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChempionResponse", Namespace="http://www.sanet.com/", Order=0)]
        public GetChempionResponseBody Body;
        
        public GetChempionResponse() {
        }
        
        public GetChempionResponse(GetChempionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class GetChempionResponseBody {
        
        [DataMember(Order=0)]
        public bool GetChempionResult;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetChempionResponseBody() {
        }
        
        public GetChempionResponseBody(bool GetChempionResult, string Name, string Score) {
            this.GetChempionResult = GetChempionResult;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastWeekChempionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastWeekChempion", Namespace="http://www.sanet.com/", Order=0)]
        public GetLastWeekChempionRequestBody Body;
        
        public GetLastWeekChempionRequest() {
        }
        
        public GetLastWeekChempionRequest(GetLastWeekChempionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class GetLastWeekChempionRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string rules;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetLastWeekChempionRequestBody() {
        }
        
        public GetLastWeekChempionRequestBody(string rules, string Name, string Score) {
            this.rules = rules;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastWeekChempionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastWeekChempionResponse", Namespace="http://www.sanet.com/", Order=0)]
        public GetLastWeekChempionResponseBody Body;
        
        public GetLastWeekChempionResponse() {
        }
        
        public GetLastWeekChempionResponse(GetLastWeekChempionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class GetLastWeekChempionResponseBody {
        
        [DataMember(Order=0)]
        public bool GetLastWeekChempionResult;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetLastWeekChempionResponseBody() {
        }
        
        public GetLastWeekChempionResponseBody(bool GetLastWeekChempionResult, string Name, string Score) {
            this.GetLastWeekChempionResult = GetLastWeekChempionResult;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastDayChempionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastDayChempion", Namespace="http://www.sanet.com/", Order=0)]
        public GetLastDayChempionRequestBody Body;
        
        public GetLastDayChempionRequest() {
        }
        
        public GetLastDayChempionRequest(GetLastDayChempionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class GetLastDayChempionRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string rules;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetLastDayChempionRequestBody() {
        }
        
        public GetLastDayChempionRequestBody(string rules, string Name, string Score) {
            this.rules = rules;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastDayChempionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastDayChempionResponse", Namespace="http://www.sanet.com/", Order=0)]
        public GetLastDayChempionResponseBody Body;
        
        public GetLastDayChempionResponse() {
        }
        
        public GetLastDayChempionResponse(GetLastDayChempionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class GetLastDayChempionResponseBody {
        
        [DataMember(Order=0)]
        public bool GetLastDayChempionResult;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetLastDayChempionResponseBody() {
        }
        
        public GetLastDayChempionResponseBody(bool GetLastDayChempionResult, string Name, string Score) {
            this.GetLastDayChempionResult = GetLastDayChempionResult;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayersMagicsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayersMagics", Namespace="http://www.sanet.com/", Order=0)]
        public GetPlayersMagicsRequestBody Body;
        
        public GetPlayersMagicsRequest() {
        }
        
        public GetPlayersMagicsRequest(GetPlayersMagicsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class GetPlayersMagicsRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [DataMember(Order=2)]
        public int rolls;
        
        [DataMember(Order=3)]
        public int manuals;
        
        [DataMember(Order=4)]
        public int resets;
        
        public GetPlayersMagicsRequestBody() {
        }
        
        public GetPlayersMagicsRequestBody(string username, string pass, int rolls, int manuals, int resets) {
            this.username = username;
            this.pass = pass;
            this.rolls = rolls;
            this.manuals = manuals;
            this.resets = resets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayersMagicsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayersMagicsResponse", Namespace="http://www.sanet.com/", Order=0)]
        public GetPlayersMagicsResponseBody Body;
        
        public GetPlayersMagicsResponse() {
        }
        
        public GetPlayersMagicsResponse(GetPlayersMagicsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class GetPlayersMagicsResponseBody {
        
        [DataMember(Order=0)]
        public bool GetPlayersMagicsResult;
        
        [DataMember(Order=1)]
        public int rolls;
        
        [DataMember(Order=2)]
        public int manuals;
        
        [DataMember(Order=3)]
        public int resets;
        
        public GetPlayersMagicsResponseBody() {
        }
        
        public GetPlayersMagicsResponseBody(bool GetPlayersMagicsResult, int rolls, int manuals, int resets) {
            this.GetPlayersMagicsResult = GetPlayersMagicsResult;
            this.rolls = rolls;
            this.manuals = manuals;
            this.resets = resets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPlayersMagicsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPlayersMagics", Namespace="http://www.sanet.com/", Order=0)]
        public AddPlayersMagicsRequestBody Body;
        
        public AddPlayersMagicsRequest() {
        }
        
        public AddPlayersMagicsRequest(AddPlayersMagicsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class AddPlayersMagicsRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string rolls;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string manuals;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public string resets;
        
        public AddPlayersMagicsRequestBody() {
        }
        
        public AddPlayersMagicsRequestBody(string username, string pass, string rolls, string manuals, string resets) {
            this.username = username;
            this.pass = pass;
            this.rolls = rolls;
            this.manuals = manuals;
            this.resets = resets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPlayersMagicsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPlayersMagicsResponse", Namespace="http://www.sanet.com/", Order=0)]
        public AddPlayersMagicsResponseBody Body;
        
        public AddPlayersMagicsResponse() {
        }
        
        public AddPlayersMagicsResponse(AddPlayersMagicsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [DataContract(Namespace="http://www.sanet.com/")]
    public partial class AddPlayersMagicsResponseBody {
        
        [DataMember(Order=0)]
        public bool AddPlayersMagicsResult;
        
        public AddPlayersMagicsResponseBody() {
        }
        
        public AddPlayersMagicsResponseBody(bool AddPlayersMagicsResult) {
            this.AddPlayersMagicsResult = AddPlayersMagicsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KniffelServiceSoapChannel : KniffelServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PutScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PutScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PutScoreResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PutScoreResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PutScoreIntoTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PutScoreIntoTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PutScoreIntoTableResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PutScoreIntoTableResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PutScoreIntoTableWithPicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PutScoreIntoTableWithPicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PutScoreIntoTableWithPicResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PutScoreIntoTableWithPicResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PutScoreIntoTableWithPicPureNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PutScoreIntoTableWithPicPureNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PutScoreIntoTableWithPicPureNameResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PutScoreIntoTableWithPicPureNameResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PutOnlineServerLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PutOnlineServerLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PutOnlineServerLogResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PutOnlineServerLogResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTopPlayersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTopPlayersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GetTopPlayersResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GetTopPlayersResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetChempionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetChempionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GetChempionResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GetChempionResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLastWeekChempionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLastWeekChempionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GetLastWeekChempionResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GetLastWeekChempionResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLastDayChempionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLastDayChempionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GetLastDayChempionResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GetLastDayChempionResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPlayersMagicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPlayersMagicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GetPlayersMagicsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GetPlayersMagicsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddPlayersMagicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddPlayersMagicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AddPlayersMagicsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AddPlayersMagicsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KniffelServiceSoapClient : System.ServiceModel.ClientBase<KniffelServiceSoap>, KniffelServiceSoap {
        
        private BeginOperationDelegate onBeginPutScoreDelegate;
        
        private EndOperationDelegate onEndPutScoreDelegate;
        
        private System.Threading.SendOrPostCallback onPutScoreCompletedDelegate;
        
        private BeginOperationDelegate onBeginPutScoreIntoTableDelegate;
        
        private EndOperationDelegate onEndPutScoreIntoTableDelegate;
        
        private System.Threading.SendOrPostCallback onPutScoreIntoTableCompletedDelegate;
        
        private BeginOperationDelegate onBeginPutScoreIntoTableWithPicDelegate;
        
        private EndOperationDelegate onEndPutScoreIntoTableWithPicDelegate;
        
        private System.Threading.SendOrPostCallback onPutScoreIntoTableWithPicCompletedDelegate;
        
        private BeginOperationDelegate onBeginPutScoreIntoTableWithPicPureNameDelegate;
        
        private EndOperationDelegate onEndPutScoreIntoTableWithPicPureNameDelegate;
        
        private System.Threading.SendOrPostCallback onPutScoreIntoTableWithPicPureNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginPutOnlineServerLogDelegate;
        
        private EndOperationDelegate onEndPutOnlineServerLogDelegate;
        
        private System.Threading.SendOrPostCallback onPutOnlineServerLogCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTopPlayersDelegate;
        
        private EndOperationDelegate onEndGetTopPlayersDelegate;
        
        private System.Threading.SendOrPostCallback onGetTopPlayersCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetChempionDelegate;
        
        private EndOperationDelegate onEndGetChempionDelegate;
        
        private System.Threading.SendOrPostCallback onGetChempionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLastWeekChempionDelegate;
        
        private EndOperationDelegate onEndGetLastWeekChempionDelegate;
        
        private System.Threading.SendOrPostCallback onGetLastWeekChempionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLastDayChempionDelegate;
        
        private EndOperationDelegate onEndGetLastDayChempionDelegate;
        
        private System.Threading.SendOrPostCallback onGetLastDayChempionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPlayersMagicsDelegate;
        
        private EndOperationDelegate onEndGetPlayersMagicsDelegate;
        
        private System.Threading.SendOrPostCallback onGetPlayersMagicsCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddPlayersMagicsDelegate;
        
        private EndOperationDelegate onEndAddPlayersMagicsDelegate;
        
        private System.Threading.SendOrPostCallback onAddPlayersMagicsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public KniffelServiceSoapClient() {
        }
        
        public KniffelServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KniffelServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KniffelServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KniffelServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<PutScoreCompletedEventArgs> PutScoreCompleted;
        
        public event System.EventHandler<PutScoreIntoTableCompletedEventArgs> PutScoreIntoTableCompleted;
        
        public event System.EventHandler<PutScoreIntoTableWithPicCompletedEventArgs> PutScoreIntoTableWithPicCompleted;
        
        public event System.EventHandler<PutScoreIntoTableWithPicPureNameCompletedEventArgs> PutScoreIntoTableWithPicPureNameCompleted;
        
        public event System.EventHandler<PutOnlineServerLogCompletedEventArgs> PutOnlineServerLogCompleted;
        
        public event System.EventHandler<GetTopPlayersCompletedEventArgs> GetTopPlayersCompleted;
        
        public event System.EventHandler<GetChempionCompletedEventArgs> GetChempionCompleted;
        
        public event System.EventHandler<GetLastWeekChempionCompletedEventArgs> GetLastWeekChempionCompleted;
        
        public event System.EventHandler<GetLastDayChempionCompletedEventArgs> GetLastDayChempionCompleted;
        
        public event System.EventHandler<GetPlayersMagicsCompletedEventArgs> GetPlayersMagicsCompleted;
        
        public event System.EventHandler<AddPlayersMagicsCompletedEventArgs> AddPlayersMagicsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KniffelServiceSoap.BeginPutScore(PutScoreRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPutScore(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PutScoreResponse KniffelServiceSoap.EndPutScore(System.IAsyncResult result) {
            return base.Channel.EndPutScore(result);
        }
        
        private System.IAsyncResult OnBeginPutScore(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PutScoreRequest request = ((PutScoreRequest)(inValues[0]));
            return ((KniffelServiceSoap)(this)).BeginPutScore(request, callback, asyncState);
        }
        
        private object[] OnEndPutScore(System.IAsyncResult result) {
            PutScoreResponse retVal = ((KniffelServiceSoap)(this)).EndPutScore(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPutScoreCompleted(object state) {
            if ((this.PutScoreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PutScoreCompleted(this, new PutScoreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PutScoreAsync(PutScoreRequest request) {
            this.PutScoreAsync(request, null);
        }
        
        public void PutScoreAsync(PutScoreRequest request, object userState) {
            if ((this.onBeginPutScoreDelegate == null)) {
                this.onBeginPutScoreDelegate = new BeginOperationDelegate(this.OnBeginPutScore);
            }
            if ((this.onEndPutScoreDelegate == null)) {
                this.onEndPutScoreDelegate = new EndOperationDelegate(this.OnEndPutScore);
            }
            if ((this.onPutScoreCompletedDelegate == null)) {
                this.onPutScoreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPutScoreCompleted);
            }
            base.InvokeAsync(this.onBeginPutScoreDelegate, new object[] {
                        request}, this.onEndPutScoreDelegate, this.onPutScoreCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KniffelServiceSoap.BeginPutScoreIntoTable(PutScoreIntoTableRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPutScoreIntoTable(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PutScoreIntoTableResponse KniffelServiceSoap.EndPutScoreIntoTable(System.IAsyncResult result) {
            return base.Channel.EndPutScoreIntoTable(result);
        }
        
        private System.IAsyncResult OnBeginPutScoreIntoTable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PutScoreIntoTableRequest request = ((PutScoreIntoTableRequest)(inValues[0]));
            return ((KniffelServiceSoap)(this)).BeginPutScoreIntoTable(request, callback, asyncState);
        }
        
        private object[] OnEndPutScoreIntoTable(System.IAsyncResult result) {
            PutScoreIntoTableResponse retVal = ((KniffelServiceSoap)(this)).EndPutScoreIntoTable(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPutScoreIntoTableCompleted(object state) {
            if ((this.PutScoreIntoTableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PutScoreIntoTableCompleted(this, new PutScoreIntoTableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PutScoreIntoTableAsync(PutScoreIntoTableRequest request) {
            this.PutScoreIntoTableAsync(request, null);
        }
        
        public void PutScoreIntoTableAsync(PutScoreIntoTableRequest request, object userState) {
            if ((this.onBeginPutScoreIntoTableDelegate == null)) {
                this.onBeginPutScoreIntoTableDelegate = new BeginOperationDelegate(this.OnBeginPutScoreIntoTable);
            }
            if ((this.onEndPutScoreIntoTableDelegate == null)) {
                this.onEndPutScoreIntoTableDelegate = new EndOperationDelegate(this.OnEndPutScoreIntoTable);
            }
            if ((this.onPutScoreIntoTableCompletedDelegate == null)) {
                this.onPutScoreIntoTableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPutScoreIntoTableCompleted);
            }
            base.InvokeAsync(this.onBeginPutScoreIntoTableDelegate, new object[] {
                        request}, this.onEndPutScoreIntoTableDelegate, this.onPutScoreIntoTableCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KniffelServiceSoap.BeginPutScoreIntoTableWithPic(PutScoreIntoTableWithPicRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPutScoreIntoTableWithPic(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PutScoreIntoTableWithPicResponse KniffelServiceSoap.EndPutScoreIntoTableWithPic(System.IAsyncResult result) {
            return base.Channel.EndPutScoreIntoTableWithPic(result);
        }
        
        private System.IAsyncResult OnBeginPutScoreIntoTableWithPic(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PutScoreIntoTableWithPicRequest request = ((PutScoreIntoTableWithPicRequest)(inValues[0]));
            return ((KniffelServiceSoap)(this)).BeginPutScoreIntoTableWithPic(request, callback, asyncState);
        }
        
        private object[] OnEndPutScoreIntoTableWithPic(System.IAsyncResult result) {
            PutScoreIntoTableWithPicResponse retVal = ((KniffelServiceSoap)(this)).EndPutScoreIntoTableWithPic(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPutScoreIntoTableWithPicCompleted(object state) {
            if ((this.PutScoreIntoTableWithPicCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PutScoreIntoTableWithPicCompleted(this, new PutScoreIntoTableWithPicCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PutScoreIntoTableWithPicAsync(PutScoreIntoTableWithPicRequest request) {
            this.PutScoreIntoTableWithPicAsync(request, null);
        }
        
        public void PutScoreIntoTableWithPicAsync(PutScoreIntoTableWithPicRequest request, object userState) {
            if ((this.onBeginPutScoreIntoTableWithPicDelegate == null)) {
                this.onBeginPutScoreIntoTableWithPicDelegate = new BeginOperationDelegate(this.OnBeginPutScoreIntoTableWithPic);
            }
            if ((this.onEndPutScoreIntoTableWithPicDelegate == null)) {
                this.onEndPutScoreIntoTableWithPicDelegate = new EndOperationDelegate(this.OnEndPutScoreIntoTableWithPic);
            }
            if ((this.onPutScoreIntoTableWithPicCompletedDelegate == null)) {
                this.onPutScoreIntoTableWithPicCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPutScoreIntoTableWithPicCompleted);
            }
            base.InvokeAsync(this.onBeginPutScoreIntoTableWithPicDelegate, new object[] {
                        request}, this.onEndPutScoreIntoTableWithPicDelegate, this.onPutScoreIntoTableWithPicCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KniffelServiceSoap.BeginPutScoreIntoTableWithPicPureName(PutScoreIntoTableWithPicPureNameRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPutScoreIntoTableWithPicPureName(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PutScoreIntoTableWithPicPureNameResponse KniffelServiceSoap.EndPutScoreIntoTableWithPicPureName(System.IAsyncResult result) {
            return base.Channel.EndPutScoreIntoTableWithPicPureName(result);
        }
        
        private System.IAsyncResult OnBeginPutScoreIntoTableWithPicPureName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PutScoreIntoTableWithPicPureNameRequest request = ((PutScoreIntoTableWithPicPureNameRequest)(inValues[0]));
            return ((KniffelServiceSoap)(this)).BeginPutScoreIntoTableWithPicPureName(request, callback, asyncState);
        }
        
        private object[] OnEndPutScoreIntoTableWithPicPureName(System.IAsyncResult result) {
            PutScoreIntoTableWithPicPureNameResponse retVal = ((KniffelServiceSoap)(this)).EndPutScoreIntoTableWithPicPureName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPutScoreIntoTableWithPicPureNameCompleted(object state) {
            if ((this.PutScoreIntoTableWithPicPureNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PutScoreIntoTableWithPicPureNameCompleted(this, new PutScoreIntoTableWithPicPureNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PutScoreIntoTableWithPicPureNameAsync(PutScoreIntoTableWithPicPureNameRequest request) {
            this.PutScoreIntoTableWithPicPureNameAsync(request, null);
        }
        
        public void PutScoreIntoTableWithPicPureNameAsync(PutScoreIntoTableWithPicPureNameRequest request, object userState) {
            if ((this.onBeginPutScoreIntoTableWithPicPureNameDelegate == null)) {
                this.onBeginPutScoreIntoTableWithPicPureNameDelegate = new BeginOperationDelegate(this.OnBeginPutScoreIntoTableWithPicPureName);
            }
            if ((this.onEndPutScoreIntoTableWithPicPureNameDelegate == null)) {
                this.onEndPutScoreIntoTableWithPicPureNameDelegate = new EndOperationDelegate(this.OnEndPutScoreIntoTableWithPicPureName);
            }
            if ((this.onPutScoreIntoTableWithPicPureNameCompletedDelegate == null)) {
                this.onPutScoreIntoTableWithPicPureNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPutScoreIntoTableWithPicPureNameCompleted);
            }
            base.InvokeAsync(this.onBeginPutScoreIntoTableWithPicPureNameDelegate, new object[] {
                        request}, this.onEndPutScoreIntoTableWithPicPureNameDelegate, this.onPutScoreIntoTableWithPicPureNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KniffelServiceSoap.BeginPutOnlineServerLog(PutOnlineServerLogRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPutOnlineServerLog(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PutOnlineServerLogResponse KniffelServiceSoap.EndPutOnlineServerLog(System.IAsyncResult result) {
            return base.Channel.EndPutOnlineServerLog(result);
        }
        
        private System.IAsyncResult OnBeginPutOnlineServerLog(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PutOnlineServerLogRequest request = ((PutOnlineServerLogRequest)(inValues[0]));
            return ((KniffelServiceSoap)(this)).BeginPutOnlineServerLog(request, callback, asyncState);
        }
        
        private object[] OnEndPutOnlineServerLog(System.IAsyncResult result) {
            PutOnlineServerLogResponse retVal = ((KniffelServiceSoap)(this)).EndPutOnlineServerLog(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPutOnlineServerLogCompleted(object state) {
            if ((this.PutOnlineServerLogCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PutOnlineServerLogCompleted(this, new PutOnlineServerLogCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PutOnlineServerLogAsync(PutOnlineServerLogRequest request) {
            this.PutOnlineServerLogAsync(request, null);
        }
        
        public void PutOnlineServerLogAsync(PutOnlineServerLogRequest request, object userState) {
            if ((this.onBeginPutOnlineServerLogDelegate == null)) {
                this.onBeginPutOnlineServerLogDelegate = new BeginOperationDelegate(this.OnBeginPutOnlineServerLog);
            }
            if ((this.onEndPutOnlineServerLogDelegate == null)) {
                this.onEndPutOnlineServerLogDelegate = new EndOperationDelegate(this.OnEndPutOnlineServerLog);
            }
            if ((this.onPutOnlineServerLogCompletedDelegate == null)) {
                this.onPutOnlineServerLogCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPutOnlineServerLogCompleted);
            }
            base.InvokeAsync(this.onBeginPutOnlineServerLogDelegate, new object[] {
                        request}, this.onEndPutOnlineServerLogDelegate, this.onPutOnlineServerLogCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KniffelServiceSoap.BeginGetTopPlayers(GetTopPlayersRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTopPlayers(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetTopPlayersResponse KniffelServiceSoap.EndGetTopPlayers(System.IAsyncResult result) {
            return base.Channel.EndGetTopPlayers(result);
        }
        
        private System.IAsyncResult OnBeginGetTopPlayers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GetTopPlayersRequest request = ((GetTopPlayersRequest)(inValues[0]));
            return ((KniffelServiceSoap)(this)).BeginGetTopPlayers(request, callback, asyncState);
        }
        
        private object[] OnEndGetTopPlayers(System.IAsyncResult result) {
            GetTopPlayersResponse retVal = ((KniffelServiceSoap)(this)).EndGetTopPlayers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTopPlayersCompleted(object state) {
            if ((this.GetTopPlayersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTopPlayersCompleted(this, new GetTopPlayersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTopPlayersAsync(GetTopPlayersRequest request) {
            this.GetTopPlayersAsync(request, null);
        }
        
        public void GetTopPlayersAsync(GetTopPlayersRequest request, object userState) {
            if ((this.onBeginGetTopPlayersDelegate == null)) {
                this.onBeginGetTopPlayersDelegate = new BeginOperationDelegate(this.OnBeginGetTopPlayers);
            }
            if ((this.onEndGetTopPlayersDelegate == null)) {
                this.onEndGetTopPlayersDelegate = new EndOperationDelegate(this.OnEndGetTopPlayers);
            }
            if ((this.onGetTopPlayersCompletedDelegate == null)) {
                this.onGetTopPlayersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTopPlayersCompleted);
            }
            base.InvokeAsync(this.onBeginGetTopPlayersDelegate, new object[] {
                        request}, this.onEndGetTopPlayersDelegate, this.onGetTopPlayersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KniffelServiceSoap.BeginGetChempion(GetChempionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetChempion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetChempionResponse KniffelServiceSoap.EndGetChempion(System.IAsyncResult result) {
            return base.Channel.EndGetChempion(result);
        }
        
        private System.IAsyncResult OnBeginGetChempion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GetChempionRequest request = ((GetChempionRequest)(inValues[0]));
            return ((KniffelServiceSoap)(this)).BeginGetChempion(request, callback, asyncState);
        }
        
        private object[] OnEndGetChempion(System.IAsyncResult result) {
            GetChempionResponse retVal = ((KniffelServiceSoap)(this)).EndGetChempion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetChempionCompleted(object state) {
            if ((this.GetChempionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetChempionCompleted(this, new GetChempionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetChempionAsync(GetChempionRequest request) {
            this.GetChempionAsync(request, null);
        }
        
        public void GetChempionAsync(GetChempionRequest request, object userState) {
            if ((this.onBeginGetChempionDelegate == null)) {
                this.onBeginGetChempionDelegate = new BeginOperationDelegate(this.OnBeginGetChempion);
            }
            if ((this.onEndGetChempionDelegate == null)) {
                this.onEndGetChempionDelegate = new EndOperationDelegate(this.OnEndGetChempion);
            }
            if ((this.onGetChempionCompletedDelegate == null)) {
                this.onGetChempionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetChempionCompleted);
            }
            base.InvokeAsync(this.onBeginGetChempionDelegate, new object[] {
                        request}, this.onEndGetChempionDelegate, this.onGetChempionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KniffelServiceSoap.BeginGetLastWeekChempion(GetLastWeekChempionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLastWeekChempion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetLastWeekChempionResponse KniffelServiceSoap.EndGetLastWeekChempion(System.IAsyncResult result) {
            return base.Channel.EndGetLastWeekChempion(result);
        }
        
        private System.IAsyncResult OnBeginGetLastWeekChempion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GetLastWeekChempionRequest request = ((GetLastWeekChempionRequest)(inValues[0]));
            return ((KniffelServiceSoap)(this)).BeginGetLastWeekChempion(request, callback, asyncState);
        }
        
        private object[] OnEndGetLastWeekChempion(System.IAsyncResult result) {
            GetLastWeekChempionResponse retVal = ((KniffelServiceSoap)(this)).EndGetLastWeekChempion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLastWeekChempionCompleted(object state) {
            if ((this.GetLastWeekChempionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLastWeekChempionCompleted(this, new GetLastWeekChempionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLastWeekChempionAsync(GetLastWeekChempionRequest request) {
            this.GetLastWeekChempionAsync(request, null);
        }
        
        public void GetLastWeekChempionAsync(GetLastWeekChempionRequest request, object userState) {
            if ((this.onBeginGetLastWeekChempionDelegate == null)) {
                this.onBeginGetLastWeekChempionDelegate = new BeginOperationDelegate(this.OnBeginGetLastWeekChempion);
            }
            if ((this.onEndGetLastWeekChempionDelegate == null)) {
                this.onEndGetLastWeekChempionDelegate = new EndOperationDelegate(this.OnEndGetLastWeekChempion);
            }
            if ((this.onGetLastWeekChempionCompletedDelegate == null)) {
                this.onGetLastWeekChempionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLastWeekChempionCompleted);
            }
            base.InvokeAsync(this.onBeginGetLastWeekChempionDelegate, new object[] {
                        request}, this.onEndGetLastWeekChempionDelegate, this.onGetLastWeekChempionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KniffelServiceSoap.BeginGetLastDayChempion(GetLastDayChempionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLastDayChempion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetLastDayChempionResponse KniffelServiceSoap.EndGetLastDayChempion(System.IAsyncResult result) {
            return base.Channel.EndGetLastDayChempion(result);
        }
        
        private System.IAsyncResult OnBeginGetLastDayChempion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GetLastDayChempionRequest request = ((GetLastDayChempionRequest)(inValues[0]));
            return ((KniffelServiceSoap)(this)).BeginGetLastDayChempion(request, callback, asyncState);
        }
        
        private object[] OnEndGetLastDayChempion(System.IAsyncResult result) {
            GetLastDayChempionResponse retVal = ((KniffelServiceSoap)(this)).EndGetLastDayChempion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLastDayChempionCompleted(object state) {
            if ((this.GetLastDayChempionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLastDayChempionCompleted(this, new GetLastDayChempionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLastDayChempionAsync(GetLastDayChempionRequest request) {
            this.GetLastDayChempionAsync(request, null);
        }
        
        public void GetLastDayChempionAsync(GetLastDayChempionRequest request, object userState) {
            if ((this.onBeginGetLastDayChempionDelegate == null)) {
                this.onBeginGetLastDayChempionDelegate = new BeginOperationDelegate(this.OnBeginGetLastDayChempion);
            }
            if ((this.onEndGetLastDayChempionDelegate == null)) {
                this.onEndGetLastDayChempionDelegate = new EndOperationDelegate(this.OnEndGetLastDayChempion);
            }
            if ((this.onGetLastDayChempionCompletedDelegate == null)) {
                this.onGetLastDayChempionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLastDayChempionCompleted);
            }
            base.InvokeAsync(this.onBeginGetLastDayChempionDelegate, new object[] {
                        request}, this.onEndGetLastDayChempionDelegate, this.onGetLastDayChempionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KniffelServiceSoap.BeginGetPlayersMagics(GetPlayersMagicsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPlayersMagics(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetPlayersMagicsResponse KniffelServiceSoap.EndGetPlayersMagics(System.IAsyncResult result) {
            return base.Channel.EndGetPlayersMagics(result);
        }
        
        private System.IAsyncResult OnBeginGetPlayersMagics(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GetPlayersMagicsRequest request = ((GetPlayersMagicsRequest)(inValues[0]));
            return ((KniffelServiceSoap)(this)).BeginGetPlayersMagics(request, callback, asyncState);
        }
        
        private object[] OnEndGetPlayersMagics(System.IAsyncResult result) {
            GetPlayersMagicsResponse retVal = ((KniffelServiceSoap)(this)).EndGetPlayersMagics(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPlayersMagicsCompleted(object state) {
            if ((this.GetPlayersMagicsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPlayersMagicsCompleted(this, new GetPlayersMagicsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPlayersMagicsAsync(GetPlayersMagicsRequest request) {
            this.GetPlayersMagicsAsync(request, null);
        }
        
        public void GetPlayersMagicsAsync(GetPlayersMagicsRequest request, object userState) {
            if ((this.onBeginGetPlayersMagicsDelegate == null)) {
                this.onBeginGetPlayersMagicsDelegate = new BeginOperationDelegate(this.OnBeginGetPlayersMagics);
            }
            if ((this.onEndGetPlayersMagicsDelegate == null)) {
                this.onEndGetPlayersMagicsDelegate = new EndOperationDelegate(this.OnEndGetPlayersMagics);
            }
            if ((this.onGetPlayersMagicsCompletedDelegate == null)) {
                this.onGetPlayersMagicsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPlayersMagicsCompleted);
            }
            base.InvokeAsync(this.onBeginGetPlayersMagicsDelegate, new object[] {
                        request}, this.onEndGetPlayersMagicsDelegate, this.onGetPlayersMagicsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult KniffelServiceSoap.BeginAddPlayersMagics(AddPlayersMagicsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddPlayersMagics(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddPlayersMagicsResponse KniffelServiceSoap.EndAddPlayersMagics(System.IAsyncResult result) {
            return base.Channel.EndAddPlayersMagics(result);
        }
        
        private System.IAsyncResult OnBeginAddPlayersMagics(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AddPlayersMagicsRequest request = ((AddPlayersMagicsRequest)(inValues[0]));
            return ((KniffelServiceSoap)(this)).BeginAddPlayersMagics(request, callback, asyncState);
        }
        
        private object[] OnEndAddPlayersMagics(System.IAsyncResult result) {
            AddPlayersMagicsResponse retVal = ((KniffelServiceSoap)(this)).EndAddPlayersMagics(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddPlayersMagicsCompleted(object state) {
            if ((this.AddPlayersMagicsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddPlayersMagicsCompleted(this, new AddPlayersMagicsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddPlayersMagicsAsync(AddPlayersMagicsRequest request) {
            this.AddPlayersMagicsAsync(request, null);
        }
        
        public void AddPlayersMagicsAsync(AddPlayersMagicsRequest request, object userState) {
            if ((this.onBeginAddPlayersMagicsDelegate == null)) {
                this.onBeginAddPlayersMagicsDelegate = new BeginOperationDelegate(this.OnBeginAddPlayersMagics);
            }
            if ((this.onEndAddPlayersMagicsDelegate == null)) {
                this.onEndAddPlayersMagicsDelegate = new EndOperationDelegate(this.OnEndAddPlayersMagics);
            }
            if ((this.onAddPlayersMagicsCompletedDelegate == null)) {
                this.onAddPlayersMagicsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddPlayersMagicsCompleted);
            }
            base.InvokeAsync(this.onBeginAddPlayersMagicsDelegate, new object[] {
                        request}, this.onEndAddPlayersMagicsDelegate, this.onAddPlayersMagicsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override KniffelServiceSoap CreateChannel() {
            return new KniffelServiceSoapClientChannel(this);
        }
        
        private class KniffelServiceSoapClientChannel : ChannelBase<KniffelServiceSoap>, KniffelServiceSoap {
            
            public KniffelServiceSoapClientChannel(System.ServiceModel.ClientBase<KniffelServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginPutScore(PutScoreRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("PutScore", _args, callback, asyncState);
                return _result;
            }
            
            public PutScoreResponse EndPutScore(System.IAsyncResult result) {
                object[] _args = new object[0];
                PutScoreResponse _result = ((PutScoreResponse)(base.EndInvoke("PutScore", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPutScoreIntoTable(PutScoreIntoTableRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("PutScoreIntoTable", _args, callback, asyncState);
                return _result;
            }
            
            public PutScoreIntoTableResponse EndPutScoreIntoTable(System.IAsyncResult result) {
                object[] _args = new object[0];
                PutScoreIntoTableResponse _result = ((PutScoreIntoTableResponse)(base.EndInvoke("PutScoreIntoTable", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPutScoreIntoTableWithPic(PutScoreIntoTableWithPicRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("PutScoreIntoTableWithPic", _args, callback, asyncState);
                return _result;
            }
            
            public PutScoreIntoTableWithPicResponse EndPutScoreIntoTableWithPic(System.IAsyncResult result) {
                object[] _args = new object[0];
                PutScoreIntoTableWithPicResponse _result = ((PutScoreIntoTableWithPicResponse)(base.EndInvoke("PutScoreIntoTableWithPic", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPutScoreIntoTableWithPicPureName(PutScoreIntoTableWithPicPureNameRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("PutScoreIntoTableWithPicPureName", _args, callback, asyncState);
                return _result;
            }
            
            public PutScoreIntoTableWithPicPureNameResponse EndPutScoreIntoTableWithPicPureName(System.IAsyncResult result) {
                object[] _args = new object[0];
                PutScoreIntoTableWithPicPureNameResponse _result = ((PutScoreIntoTableWithPicPureNameResponse)(base.EndInvoke("PutScoreIntoTableWithPicPureName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPutOnlineServerLog(PutOnlineServerLogRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("PutOnlineServerLog", _args, callback, asyncState);
                return _result;
            }
            
            public PutOnlineServerLogResponse EndPutOnlineServerLog(System.IAsyncResult result) {
                object[] _args = new object[0];
                PutOnlineServerLogResponse _result = ((PutOnlineServerLogResponse)(base.EndInvoke("PutOnlineServerLog", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTopPlayers(GetTopPlayersRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetTopPlayers", _args, callback, asyncState);
                return _result;
            }
            
            public GetTopPlayersResponse EndGetTopPlayers(System.IAsyncResult result) {
                object[] _args = new object[0];
                GetTopPlayersResponse _result = ((GetTopPlayersResponse)(base.EndInvoke("GetTopPlayers", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetChempion(GetChempionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetChempion", _args, callback, asyncState);
                return _result;
            }
            
            public GetChempionResponse EndGetChempion(System.IAsyncResult result) {
                object[] _args = new object[0];
                GetChempionResponse _result = ((GetChempionResponse)(base.EndInvoke("GetChempion", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLastWeekChempion(GetLastWeekChempionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetLastWeekChempion", _args, callback, asyncState);
                return _result;
            }
            
            public GetLastWeekChempionResponse EndGetLastWeekChempion(System.IAsyncResult result) {
                object[] _args = new object[0];
                GetLastWeekChempionResponse _result = ((GetLastWeekChempionResponse)(base.EndInvoke("GetLastWeekChempion", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLastDayChempion(GetLastDayChempionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetLastDayChempion", _args, callback, asyncState);
                return _result;
            }
            
            public GetLastDayChempionResponse EndGetLastDayChempion(System.IAsyncResult result) {
                object[] _args = new object[0];
                GetLastDayChempionResponse _result = ((GetLastDayChempionResponse)(base.EndInvoke("GetLastDayChempion", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPlayersMagics(GetPlayersMagicsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetPlayersMagics", _args, callback, asyncState);
                return _result;
            }
            
            public GetPlayersMagicsResponse EndGetPlayersMagics(System.IAsyncResult result) {
                object[] _args = new object[0];
                GetPlayersMagicsResponse _result = ((GetPlayersMagicsResponse)(base.EndInvoke("GetPlayersMagics", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddPlayersMagics(AddPlayersMagicsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AddPlayersMagics", _args, callback, asyncState);
                return _result;
            }
            
            public AddPlayersMagicsResponse EndAddPlayersMagics(System.IAsyncResult result) {
                object[] _args = new object[0];
                AddPlayersMagicsResponse _result = ((AddPlayersMagicsResponse)(base.EndInvoke("AddPlayersMagics", _args, result)));
                return _result;
            }
        }
    }
}
