trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Web\Functions\MagicalYatzyFunctions.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: dotnet restore $(solution)
  displayName: 'Restore nuget packages'

- script: dotnet test Tests\Functions\LoginTests\LoginTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute=GeneratedCodeAttribute /p:Include=[MagicalYatzy]*
  displayName: 'Run Login tests'

- bash: |
    curl -s https://codecov.io/bash > codecov
    chmod +x codecov
    ./codecov -f "Tests\Functions\LoginTests\coverage.opencover.xml" -t $(codecov.token)
  displayName: 'Upload Login tests results'

- script: dotnet test Tests\Functions\ScoreSaverTests\ScoreSaverTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute=GeneratedCodeAttribute /p:Include=[MagicalYatzy]*
  displayName: 'Run ScoreSaver tests'

- bash: |
    curl -s https://codecov.io/bash > codecov
    chmod +x codecov
    ./codecov -f "Tests\Functions\ScoreSaverTests\coverage.opencover.xml" -t $(codecov.token)
  displayName: 'Upload ScoreSaver tests results'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Web\Functions\LoginFunction\LoginFunction.csproj'

- script: dotnet publish Web\Functions\LoginFunction\LoginFunction.csproj -c $(buildConfiguration) -v d
  displayName: 'Publish login function'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Web\Functions\LoginFunction\bin\Release\netcoreapp2.1\publish\bin\'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: 'Web\Functions\LoginFunction\bin\Release\netcoreapp2.1\publish\LoginFunction.zip'
    replaceExistingArchive: true
    verbose: true

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'BizSpark(6d9a1353-48c4-43d7-85e0-141803e550b5)'
    appType: 'functionApp'
    appName: 'magical-yatzy-dev'
    package: 'Web\Functions\LoginFunction\bin\Release\netcoreapp2.1\publish\LoginFunction.zip'
    deploymentMethod: 'auto'
