trigger:
- chore/azure-pipelines-mac

pool:
  vmImage: 'macos-latest'

variables:
  - name: solution
    value: 'MagicalYatzyXF.sln'
  - name: project
    value: 'MagicalYatzyXF/MagicalYatzyXF.UWP/MagicalYatzyXF.Mac.csproj'
  - name: buildPlatform
    value: 'x86'
  - name: buildConfiguration
    value: 'Debug'

steps:

- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use dotnet sdk 3.x'
  inputs:
    version: 3.x
    includePreviewVersions: false

- task: NuGetCommand@2
  displayName: 'Restore nuget packages'
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  displayName: 'Build Mac project'
  inputs:
    platform: '$(buildPlatform)'
    solution: '$(project)'
    configuration: '$(buildConfiguration)'
