trigger:
- develop

pool:
  vmImage: 'macOS-10.13'

steps:
- script: dotnet restore MagicalYatzyXF.sln
  displayName: 'Restore nuget packages'

- script: dotnet test Tests/MagicalYatzyTests/MagicalYatzyTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute="Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute"
  displayName: 'Run tests'

- bash: |
    curl -s https://codecov.io/bash > codecov
    chmod +x codecov
    ./codecov -f "Tests/MagicalYatzyTests/coverage.opencover.xml" -t $(codecov.token)