trigger:
- develop

pool:
  vmImage: 'macos-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 3.x'
  inputs:
    version: 3.x
    includePreviewVersions: false

- script: dotnet restore MagicalYatzyXF.sln
  displayName: 'Restore nuget packages'

- script: dotnet test Tests/MagicalYatzyDtoTests/MagicalYatzyDtoTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute=GeneratedCodeAttribute /p:Include=[MagicalYatzy]*
  displayName: 'Run DTO tests'

- bash: |
    bash <(curl -s https://codecov.io/bash) -f "Tests/MagicalYatzyDtoTests/coverage.opencover.xml" -t $(codecov.token)
  displayName: 'Upload DTO tests results'

- script: dotnet test Tests/MagicalYatzyTests/MagicalYatzyTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute=GeneratedCodeAttribute /p:Include=[MagicalYatzy]*
  displayName: 'Run Core tests'

- bash: |
    bash <(curl -s https://codecov.io/bash) -f "Tests/MagicalYatzyTests/coverage.opencover.xml" -t $(codecov.token)
  displayName: 'Upload Core tests results'