trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Web\Functions\MagicalYatzyFunctions.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: dotnet restore $(solution)
  displayName: 'Restore nuget packages'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:SkipInvalidConfigurations=true'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
