trigger:
- develop

pool:
  vmImage: 'macos-latest'

variables:
  - name: solution
    value: 'MagicalYatzyXF.sln'
  - name: project
    value: 'MagicalYatzyXF/MagicalYatzyXF.Mac/MagicalYatzyXF.Mac.csproj'
  - name: buildPlatform
    value: 'iPhoneSimulator'
  - name: buildConfiguration
    value: 'Debug'

steps:

- task: UseDotNet@2
  displayName: 'Use dotnet sdk 3.x'
  inputs:
    version: 3.x
    includePreviewVersions: false

- script: dotnet restore $(solution)
  displayName: 'Restore nuget packages'

- task: VSBuild@1
  displayName: 'Build Mac project'
  inputs:
    platform: '$(buildPlatform)'
    solution: '$(project)'
    configuration: '$(buildConfiguration)'
