trigger:
- develop

pool:
  vmImage: 'macOS-10.13'

steps:
- script: dotnet restore MagicalYatzyXF.sln
  displayName: 'Restore nuget packages'

- script: dotnet test Tests/MagicalYatzyTests/MagicalYatzyTests.csproj
  displayName: 'Run tests'

