<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>Sanet.MagicalYatzy.Avalonia</RootNamespace>
        <AssemblyName>MagicalYatzy.Avalonia</AssemblyName>
    </PropertyGroup>


    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.2" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
        <PackageReference Include="Sanet.MVVM.DI.Avalonia" Version="1.7.1211" />
        <PackageReference Include="Sanet.MVVM.Navigation.Avalonia" Version="1.7.1211" />
        <PackageReference Include="Sanet.MVVM.Views.Avalonia" Version="1.6.1211" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\MagicalYatzy.Core\MagicalYatzy.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Views\Cells\PlayerCell.axaml" />
      <UpToDateCheckInput Remove="Views\Cells\RuleCell.axaml" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Assets\Styles\White.png" />
      <EmbeddedResource Include="Assets\Styles\Red.png" />
      <EmbeddedResource Include="Assets\Styles\Blue.png" />
    </ItemGroup>
</Project>


