//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanet.MagicalYatzy.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sanet.MagicalYatzy.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutAction {
            get {
                return ResourceManager.GetString("AboutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutCaptionText {
            get {
                return ResourceManager.GetString("AboutCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About game and authors.
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to virtual dice in your device.
        /// </summary>
        internal static string AboutTextText {
            get {
                return ResourceManager.GetString("AboutTextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bot.
        /// </summary>
        internal static string AddBotLabel {
            get {
                return ResourceManager.GetString("AddBotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Player.
        /// </summary>
        internal static string AddPlayerLabel {
            get {
                return ResourceManager.GetString("AddPlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play again.
        /// </summary>
        internal static string AgainLabel {
            get {
                return ResourceManager.GetString("AgainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See whole leaderboard on the web.
        /// </summary>
        internal static string AllRecordsLabel {
            get {
                return ResourceManager.GetString("AllRecordsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, You can&apos;t connect to selected table. There is a player with the same name... Please try later. .
        /// </summary>
        internal static string AlreadyInGameMessage {
            get {
                return ResourceManager.GetString("AlreadyInGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high.
        /// </summary>
        internal static string AngHighText {
            get {
                return ResourceManager.GetString("AngHighText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low.
        /// </summary>
        internal static string AngLowText {
            get {
                return ResourceManager.GetString("AngLowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very high.
        /// </summary>
        internal static string AngVeryHighText {
            get {
                return ResourceManager.GetString("AngVeryHighText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical Yatzy.
        /// </summary>
        internal static string AppNameLabel {
            get {
                return ResourceManager.GetString("AppNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Congratulations! You got {1} Magical Artifacts as a bonus!.
        /// </summary>
        internal static string ArtifactsBonusMessage {
            get {
                return ResourceManager.GetString("ArtifactsBonusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artifacts .
        /// </summary>
        internal static string ArtifactsForLabel {
            get {
                return ResourceManager.GetString("ArtifactsForLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifacts.
        /// </summary>
        internal static string ArtifactsLabel {
            get {
                return ResourceManager.GetString("ArtifactsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to win or buy.
        /// </summary>
        internal static string ArtifactsWinBuyMessage {
            get {
                return ResourceManager.GetString("ArtifactsWinBuyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational app to learn writing. This interactive software develops fine motor skills, memory, teaches how to write Russian (Cyrillic) letters, English ABC&apos;s characters, Chinese chars, numbers and various symbols..
        /// </summary>
        internal static string AWDescription {
            get {
                return ResourceManager.GetString("AWDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best of the day.
        /// </summary>
        internal static string BestDayLabel {
            get {
                return ResourceManager.GetString("BestDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best local results.
        /// </summary>
        internal static string BestLocalLabel {
            get {
                return ResourceManager.GetString("BestLocalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best local .
        /// </summary>
        internal static string BestLocalShort {
            get {
                return ResourceManager.GetString("BestLocalShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best of the week.
        /// </summary>
        internal static string BestWeekLabel {
            get {
                return ResourceManager.GetString("BestWeekLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string BonusShort {
            get {
                return ResourceManager.GetString("BonusShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        internal static string BotNameDefault {
            get {
                return ResourceManager.GetString("BotNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy.
        /// </summary>
        internal static string BuyLabel {
            get {
                return ResourceManager.GetString("BuyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we can&apos;t join right now. Please try again later..
        /// </summary>
        internal static string CantJoinMessage {
            get {
                return ResourceManager.GetString("CantJoinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        internal static string Chance {
            get {
                return ResourceManager.GetString("Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change name.
        /// </summary>
        internal static string ChangeNameLabel {
            get {
                return ResourceManager.GetString("ChangeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password needed.
        /// </summary>
        internal static string ChangePasswordLabel {
            get {
                return ResourceManager.GetString("ChangePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string ChatPanelLabel {
            get {
                return ResourceManager.GetString("ChatPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checking....
        /// </summary>
        internal static string CheckingLabel {
            get {
                return ResourceManager.GetString("CheckingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear selection.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client:.
        /// </summary>
        internal static string ClientLabel {
            get {
                return ResourceManager.GetString("ClientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated.
        /// </summary>
        internal static string ClientOutdatedLabel {
            get {
                return ResourceManager.GetString("ClientOutdatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your game version is outdated, please update to play online..
        /// </summary>
        internal static string ClientOutdatedMessage {
            get {
                return ResourceManager.GetString("ClientOutdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string ClientUpdatedLabel {
            get {
                return ResourceManager.GetString("ClientUpdatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButtonContent {
            get {
                return ResourceManager.GetString("CloseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ContinueLabel {
            get {
                return ResourceManager.GetString("ContinueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1.49.
        /// </summary>
        internal static string Cost1Label {
            get {
                return ResourceManager.GetString("Cost1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1.99.
        /// </summary>
        internal static string Cost2Label {
            get {
                return ResourceManager.GetString("Cost2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $2.49.
        /// </summary>
        internal static string Cost3Label {
            get {
                return ResourceManager.GetString("Cost3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeletePlayerLabel {
            get {
                return ResourceManager.GetString("DeletePlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by:.
        /// </summary>
        internal static string DevelopedByText {
            get {
                return ResourceManager.GetString("DevelopedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice.
        /// </summary>
        internal static string DiceBoardLabel {
            get {
                return ResourceManager.GetString("DiceBoardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual dice you always have with you! You can use them in your favorite games, or just when you need to take a random decision.
        /// </summary>
        internal static string DiceDescription {
            get {
                return ResourceManager.GetString("DiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boring of just rolling dices?.
        /// </summary>
        internal static string DicePokerAdLine1 {
            get {
                return ResourceManager.GetString("DicePokerAdLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try our new game-.
        /// </summary>
        internal static string DicePokerAdLine2 {
            get {
                return ResourceManager.GetString("DicePokerAdLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical Yatzy:.
        /// </summary>
        internal static string DicePokerAdLine3 {
            get {
                return ResourceManager.GetString("DicePokerAdLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 sets of rules.
        /// </summary>
        internal static string DicePokerAdLine4 {
            get {
                return ResourceManager.GetString("DicePokerAdLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play with friends or bots.
        /// </summary>
        internal static string DicePokerAdLine5 {
            get {
                return ResourceManager.GetString("DicePokerAdLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to best results table.
        /// </summary>
        internal static string DicePokerAdLine6 {
            get {
                return ResourceManager.GetString("DicePokerAdLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and soon....
        /// </summary>
        internal static string DicePokerAdLine7 {
            get {
                return ResourceManager.GetString("DicePokerAdLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internet multiplayer game.
        /// </summary>
        internal static string DicePokerAdLine8 {
            get {
                return ResourceManager.GetString("DicePokerAdLine8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave game? The current state of the game will be lost..
        /// </summary>
        internal static string ExitConfirmMessage {
            get {
                return ResourceManager.GetString("ExitConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string FacebookLabel {
            get {
                return ResourceManager.GetString("FacebookLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string FBPage {
            get {
                return ResourceManager.GetString("FBPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Each new player with unique name and password gets artifacts as a bonus..
        /// </summary>
        internal static string FirstTimeBonusDescription {
            get {
                return ResourceManager.GetString("FirstTimeBonusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Game Bonus.
        /// </summary>
        internal static string FirstTimeBonusLabel {
            get {
                return ResourceManager.GetString("FirstTimeBonusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five&apos;s.
        /// </summary>
        internal static string Fives {
            get {
                return ResourceManager.GetString("Fives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string FivesShort {
            get {
                return ResourceManager.GetString("FivesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset round.
        /// </summary>
        internal static string ForthRollLabel {
            get {
                return ResourceManager.GetString("ForthRollLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical Yatzy for Windows 8.
        /// </summary>
        internal static string ForWin8Label {
            get {
                return ResourceManager.GetString("ForWin8Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical Yatzy for Windows Phone.
        /// </summary>
        internal static string ForWPLabel {
            get {
                return ResourceManager.GetString("ForWPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Of A Kind.
        /// </summary>
        internal static string FourOfAKind {
            get {
                return ResourceManager.GetString("FourOfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string FourOfAKindShort {
            get {
                return ResourceManager.GetString("FourOfAKindShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four&apos;s.
        /// </summary>
        internal static string Fours {
            get {
                return ResourceManager.GetString("Fours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string FoursShort {
            get {
                return ResourceManager.GetString("FoursShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full House.
        /// </summary>
        internal static string FullHouse {
            get {
                return ResourceManager.GetString("FullHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FH.
        /// </summary>
        internal static string FullHouseShort {
            get {
                return ResourceManager.GetString("FullHouseShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is finished!.
        /// </summary>
        internal static string GameFinishedLabel {
            get {
                return ResourceManager.GetString("GameFinishedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to get?.
        /// </summary>
        internal static string HowGetLabel {
            get {
                return ResourceManager.GetString("HowGetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical artifacts - are valuable resources and they are limited. There are several ways to get more magic:.
        /// </summary>
        internal static string HowToGetDescription {
            get {
                return ResourceManager.GetString("HowToGetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatzy!.
        /// </summary>
        internal static string Kniffel {
            get {
                return ResourceManager.GetString("Kniffel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P!.
        /// </summary>
        internal static string KniffelShort {
            get {
                return ResourceManager.GetString("KniffelShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Kids.
        /// </summary>
        internal static string krBaby {
            get {
                return ResourceManager.GetString("krBaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeric hands only and Yatzy, 7 rounds.
        /// </summary>
        internal static string krBabyShort {
            get {
                return ResourceManager.GetString("krBabyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string krExtended {
            get {
                return ResourceManager.GetString("krExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard + 100 points bonus for every additional Yatzy, Yatzy-Joker, 13 rounds.
        /// </summary>
        internal static string krExtendedShort {
            get {
                return ResourceManager.GetString("krExtendedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical.
        /// </summary>
        internal static string krMagic {
            get {
                return ResourceManager.GetString("krMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advanced + &quot;magical artifacts&quot;, 13 rounds.
        /// </summary>
        internal static string krMagicShort {
            get {
                return ResourceManager.GetString("krMagicShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string krSimple {
            get {
                return ResourceManager.GetString("krSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all hands, no bonuses, 13 rounds.
        /// </summary>
        internal static string krSimpleShort {
            get {
                return ResourceManager.GetString("krSimpleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string krStandard {
            get {
                return ResourceManager.GetString("krStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simple + 35 points bonus for 63 and higher result in numerics, 13 rounds.
        /// </summary>
        internal static string krStandardShort {
            get {
                return ResourceManager.GetString("krStandardShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Straight.
        /// </summary>
        internal static string LargeStraight {
            get {
                return ResourceManager.GetString("LargeStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LS.
        /// </summary>
        internal static string LargeStraightShort {
            get {
                return ResourceManager.GetString("LargeStraightShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later..
        /// </summary>
        internal static string LaterLabel {
            get {
                return ResourceManager.GetString("LaterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Fame.
        /// </summary>
        internal static string LeaderboardAction {
            get {
                return ResourceManager.GetString("LeaderboardAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See best results in every set of rules.
        /// </summary>
        internal static string LeaderboardDescription {
            get {
                return ResourceManager.GetString("LeaderboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string LocalLabel {
            get {
                return ResourceManager.GetString("LocalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to log in.
        /// </summary>
        internal static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Facebook.
        /// </summary>
        internal static string LoginToFBLabel {
            get {
                return ResourceManager.GetString("LoginToFBLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to log out.
        /// </summary>
        internal static string LogoutLabel {
            get {
                return ResourceManager.GetString("LogoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical artifacts raise your chances to get better hand in Magical rules. Each type of artifacts can be used only once per game. There are 3 types of artifacts:.
        /// </summary>
        internal static string MagicArtifactsDescription {
            get {
                return ResourceManager.GetString("MagicArtifactsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Allows you to get one of the unfilled poker hands (from &apos;3 of a kind&apos; to &apos;Yatzy&apos;) in random order..
        /// </summary>
        internal static string MagicRollDescription {
            get {
                return ResourceManager.GetString("MagicRollDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical Roll.
        /// </summary>
        internal static string MagicRollLabel {
            get {
                return ResourceManager.GetString("MagicRollLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard&apos;s room.
        /// </summary>
        internal static string MagicRoomLabel {
            get {
                return ResourceManager.GetString("MagicRoomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Alows you to change the value of one dice by your choice..
        /// </summary>
        internal static string ManualSetDescription {
            get {
                return ResourceManager.GetString("ManualSetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Set.
        /// </summary>
        internal static string ManualSetLabel {
            get {
                return ResourceManager.GetString("ManualSetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some icons are created in Syncfusion Metro Studio.
        /// </summary>
        internal static string MetroStudioText {
            get {
                return ResourceManager.GetString("MetroStudioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        internal static string MoreLabel {
            get {
                return ResourceManager.GetString("MoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to round.
        /// </summary>
        internal static string MoveLabel {
            get {
                return ResourceManager.GetString("MoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, network game is not ready yet.
        /// </summary>
        internal static string NetworkGameNotReadyMessage {
            get {
                return ResourceManager.GetString("NetworkGameNotReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, thanks..
        /// </summary>
        internal static string NeverLabel {
            get {
                return ResourceManager.GetString("NeverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Game.
        /// </summary>
        internal static string NewLocalGameAction {
            get {
                return ResourceManager.GetString("NewLocalGameAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new local game - alone, with friends or with bots.
        /// </summary>
        internal static string NewLocalGameDescription {
            get {
                return ResourceManager.GetString("NewLocalGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online game.
        /// </summary>
        internal static string NewOnlineGameAction {
            get {
                return ResourceManager.GetString("NewOnlineGameAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite friends and play with them over Internet.
        /// </summary>
        internal static string NewOnlineGameDescription {
            get {
                return ResourceManager.GetString("NewOnlineGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS reader for news from Belarus. All your news in one place. We already have news from main Belarus sites, and will add more..
        /// </summary>
        internal static string NewsDescription {
            get {
                return ResourceManager.GetString("NewsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Magical Artifacts.
        /// </summary>
        internal static string NoArtifactsLabel {
            get {
                return ResourceManager.GetString("NoArtifactsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} hasn&apos;t any magical artifacts. You have to get some artifacts to use advantages of the Magical rules..
        /// </summary>
        internal static string NoArtifactsMessage {
            get {
                return ResourceManager.GetString("NoArtifactsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet access. Please check your connection and try again..
        /// </summary>
        internal static string NoInetMessage {
            get {
                return ResourceManager.GetString("NoInetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no connection.
        /// </summary>
        internal static string NoInternetLabel {
            get {
                return ResourceManager.GetString("NoInternetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can’t purchase artifacts using this version for phone. Please try version for Windows 8..
        /// </summary>
        internal static string NoPurchasesMessage {
            get {
                return ResourceManager.GetString("NoPurchasesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registration is required. Just put unique username and password. We use it to protect your scores and purchases.
        /// </summary>
        internal static string NoRegistration {
            get {
                return ResourceManager.GetString("NoRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of a kind.
        /// </summary>
        internal static string OfAKind {
            get {
                return ResourceManager.GetString("OfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OffContent {
            get {
                return ResourceManager.GetString("OffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic offer..
        /// </summary>
        internal static string Offer1Description {
            get {
                return ResourceManager.GetString("Offer1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better offer. Your discount is 20%!.
        /// </summary>
        internal static string Offer2Description {
            get {
                return ResourceManager.GetString("Offer2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent offer. It&apos;s 2 times cheaper!.
        /// </summary>
        internal static string Offer3Description {
            get {
                return ResourceManager.GetString("Offer3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string OnContent {
            get {
                return ResourceManager.GetString("OnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One&apos;s.
        /// </summary>
        internal static string Ones {
            get {
                return ResourceManager.GetString("Ones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string OnesShort {
            get {
                return ResourceManager.GetString("OnesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Magical Yatzy Online.
        /// </summary>
        internal static string OnlineLinkContent {
            get {
                return ResourceManager.GetString("OnlineLinkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice Panel idea and &quot;red dice&quot; style belong to Matthew Tagliaferri..
        /// </summary>
        internal static string OnlineVersionText {
            get {
                return ResourceManager.GetString("OnlineVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, only players with unique Username and Password can buy artifacts. We need this info to secure your purchase. Please check your data on new game page. Thanks!.
        /// </summary>
        internal static string OnlyUniqueCanBuyMessage {
            get {
                return ResourceManager.GetString("OnlyUniqueCanBuyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning English and Russian writing with Sanet AllWrite.
        /// </summary>
        internal static string OtherAllWriteContent {
            get {
                return ResourceManager.GetString("OtherAllWriteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Apps.
        /// </summary>
        internal static string OtherAppsLabel {
            get {
                return ResourceManager.GetString("OtherAppsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try other apps:.
        /// </summary>
        internal static string OtherSoftText {
            get {
                return ResourceManager.GetString("OtherSoftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pairs.
        /// </summary>
        internal static string Pairs {
            get {
                return ResourceManager.GetString("Pairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best.
        /// </summary>
        internal static string PlayerBestScoreLabel {
            get {
                return ResourceManager.GetString("PlayerBestScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string PlayerBotLabelLocalized {
            get {
                return ResourceManager.GetString("PlayerBotLabelLocalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string PlayerGamesLabel {
            get {
                return ResourceManager.GetString("PlayerGamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string PlayerHumanLabelLocalized {
            get {
                return ResourceManager.GetString("PlayerHumanLabelLocalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string PlayerNameDefault {
            get {
                return ResourceManager.GetString("PlayerNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string PlayerNameLabel {
            get {
                return ResourceManager.GetString("PlayerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no name.
        /// </summary>
        internal static string PlayerNoNameLabel {
            get {
                return ResourceManager.GetString("PlayerNoNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no password.
        /// </summary>
        internal static string PlayerNoPasswordLabel {
            get {
                return ResourceManager.GetString("PlayerNoPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string PlayerPasswordLabel {
            get {
                return ResourceManager.GetString("PlayerPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        internal static string PlayerRememberLabelLocalized {
            get {
                return ResourceManager.GetString("PlayerRememberLabelLocalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string PlayersLabel {
            get {
                return ResourceManager.GetString("PlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string PlayerTotalScoreLabel {
            get {
                return ResourceManager.GetString("PlayerTotalScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        internal static string PlayerTypeLabel {
            get {
                return ResourceManager.GetString("PlayerTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Privacy Policy covers your use of this application. Magical Yatzy does not collect, store, or share any personal information, or anything related to statistics, trends, neither do we track user movements..
        /// </summary>
        internal static string Privacy1Text {
            get {
                return ResourceManager.GetString("Privacy1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application allows you to store game results on its web server, it also will show them to other users via leaderboard functionality. Magical Yatzy allows you to open web URLs from the application. The URLs might be saved by internet browsers on your device. For information regarding the information stored by these applications, please read the privacy policy of the internet browsers of your choice..
        /// </summary>
        internal static string Privacy2Text {
            get {
                return ResourceManager.GetString("Privacy2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyLabelText {
            get {
                return ResourceManager.GetString("PrivacyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy more artifacts using one of the following offers. Each offer can be used only once a day..
        /// </summary>
        internal static string PurchaseDescription {
            get {
                return ResourceManager.GetString("PurchaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Something bad happened. Please contact support service..
        /// </summary>
        internal static string PurchaseErrorMessage {
            get {
                return ResourceManager.GetString("PurchaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical offers.
        /// </summary>
        internal static string PurchaseLabel {
            get {
                return ResourceManager.GetString("PurchaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can buy magical artifacts in the store. There are several offers with very good prices!.
        /// </summary>
        internal static string PurchaseMiniDescription {
            get {
                return ResourceManager.GetString("PurchaseMiniDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string PurchaseMiniLabel {
            get {
                return ResourceManager.GetString("PurchaseMiniLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string RandomLabel {
            get {
                return ResourceManager.GetString("RandomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app if you like it.
        /// </summary>
        internal static string RateButtonContent {
            get {
                return ResourceManager.GetString("RateButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate.
        /// </summary>
        internal static string RateLabel {
            get {
                return ResourceManager.GetString("RateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Play!.
        /// </summary>
        internal static string ReadyLabel {
            get {
                return ResourceManager.GetString("ReadyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock all dice styles, remove ads.
        /// </summary>
        internal static string RemoveAdAction {
            get {
                return ResourceManager.GetString("RemoveAdAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Ad.
        /// </summary>
        internal static string RemoveAdLabel {
            get {
                return ResourceManager.GetString("RemoveAdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Allows you to replay current round (all 3 rolls). The order of  dice values will be the same..
        /// </summary>
        internal static string RerollDescription {
            get {
                return ResourceManager.GetString("RerollDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Get more artifacts for good results playing in &apos;Advanced&apos; rules. The better you play - the more artifacts you get!.
        /// </summary>
        internal static string ResultBonusDescription {
            get {
                return ResourceManager.GetString("ResultBonusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus for good results.
        /// </summary>
        internal static string ResultBonusLabel {
            get {
                return ResourceManager.GetString("ResultBonusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string ResultsTableLabel {
            get {
                return ResourceManager.GetString("ResultsTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app in the store.
        /// </summary>
        internal static string ReviewAppAction {
            get {
                return ResourceManager.GetString("ReviewAppAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ratings and reviews encourage us to release frequent updates for this app. Would you like to rate it now?.
        /// </summary>
        internal static string ReviewReminder {
            get {
                return ResourceManager.GetString("ReviewReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like this app?.
        /// </summary>
        internal static string ReviewReminderHeader {
            get {
                return ResourceManager.GetString("ReviewReminderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roll.
        /// </summary>
        internal static string roll {
            get {
                return ResourceManager.GetString("roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string RulesLabel {
            get {
                return ResourceManager.GetString("RulesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save result to the leaderboard.
        /// </summary>
        internal static string SaveScoreLabel {
            get {
                return ResourceManager.GetString("SaveScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select dice you want to change.
        /// </summary>
        internal static string SelectDiceToChangeMessage {
            get {
                return ResourceManager.GetString("SelectDiceToChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the new dice value.
        /// </summary>
        internal static string SelectNewDiceValueMessage {
            get {
                return ResourceManager.GetString("SelectNewDiceValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        internal static string SendFeedbackAction {
            get {
                return ResourceManager.GetString("SendFeedbackAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendLabel {
            get {
                return ResourceManager.GetString("SendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        internal static string ServerLabel {
            get {
                return ResourceManager.GetString("ServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENSION! {0} (UTC) server will be shut down for maintanance , network game will not be available at that time (usually just for few mins)..
        /// </summary>
        internal static string ServerMaintananceMessage {
            get {
                return ResourceManager.GetString("ServerMaintananceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string ServerOfflineLabel {
            get {
                return ResourceManager.GetString("ServerOfflineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game server is not available. Please try again later..
        /// </summary>
        internal static string ServerOfflineMessage {
            get {
                return ResourceManager.GetString("ServerOfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string ServerOnlineLabel {
            get {
                return ResourceManager.GetString("ServerOnlineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsAction {
            get {
                return ResourceManager.GetString("SettingsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Angle.
        /// </summary>
        internal static string SettingsAngleCaptionText {
            get {
                return ResourceManager.GetString("SettingsAngleCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsCaptionText {
            get {
                return ResourceManager.GetString("SettingsCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change game settings.
        /// </summary>
        internal static string SettingsDescription {
            get {
                return ResourceManager.GetString("SettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice number.
        /// </summary>
        internal static string SettingsNumbersCaptionText {
            get {
                return ResourceManager.GetString("SettingsNumbersCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation speed.
        /// </summary>
        internal static string SettingsSpeedCaptionText {
            get {
                return ResourceManager.GetString("SettingsSpeedCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice style.
        /// </summary>
        internal static string SettingsStyleCaptionText {
            get {
                return ResourceManager.GetString("SettingsStyleCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ShareApp {
            get {
                return ResourceManager.GetString("ShareApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join me in this magical game and get some luck to bit me on the leaderboard!.
        /// </summary>
        internal static string ShareDescription {
            get {
                return ResourceManager.GetString("ShareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        internal static string ShareLabel {
            get {
                return ResourceManager.GetString("ShareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join me in this exciting multiplayer game!.
        /// </summary>
        internal static string ShareMessage {
            get {
                return ResourceManager.GetString("ShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Magical Yatzy&quot; for Windows 8 .
        /// </summary>
        internal static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six&apos;s.
        /// </summary>
        internal static string Sixs {
            get {
                return ResourceManager.GetString("Sixs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string SixsShort {
            get {
                return ResourceManager.GetString("SixsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Straight.
        /// </summary>
        internal static string SmallStraight {
            get {
                return ResourceManager.GetString("SmallStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS.
        /// </summary>
        internal static string SmallStraightShort {
            get {
                return ResourceManager.GetString("SmallStraightShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string SoundLabel {
            get {
                return ResourceManager.GetString("SoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fast.
        /// </summary>
        internal static string SpeedFastText {
            get {
                return ResourceManager.GetString("SpeedFastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slow.
        /// </summary>
        internal static string SpeedSlowText {
            get {
                return ResourceManager.GetString("SpeedSlowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very fast.
        /// </summary>
        internal static string SpeedVeryFastText {
            get {
                return ResourceManager.GetString("SpeedVeryFastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very slow.
        /// </summary>
        internal static string SpeedVerySlowText {
            get {
                return ResourceManager.GetString("SpeedVerySlowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game!.
        /// </summary>
        internal static string StartGameButton {
            get {
                return ResourceManager.GetString("StartGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Game.
        /// </summary>
        internal static string StartNewGameMessage {
            get {
                return ResourceManager.GetString("StartNewGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical support service:.
        /// </summary>
        internal static string SupportText {
            get {
                return ResourceManager.GetString("SupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string TablesLabel {
            get {
                return ResourceManager.GetString("TablesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to Apply.
        /// </summary>
        internal static string TapToApplyLabel {
            get {
                return ResourceManager.GetString("TapToApplyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to change.
        /// </summary>
        internal static string TapToChangeLabel {
            get {
                return ResourceManager.GetString("TapToChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Of A Kind.
        /// </summary>
        internal static string ThreeOfAKind {
            get {
                return ResourceManager.GetString("ThreeOfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Т.
        /// </summary>
        internal static string ThreeOfAKindShort {
            get {
                return ResourceManager.GetString("ThreeOfAKindShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three&apos;s.
        /// </summary>
        internal static string Threes {
            get {
                return ResourceManager.GetString("Threes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string ThreesShort {
            get {
                return ResourceManager.GetString("ThreesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch.
        /// </summary>
        internal static string TotalShort {
            get {
                return ResourceManager.GetString("TotalShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two&apos;s.
        /// </summary>
        internal static string Twos {
            get {
                return ResourceManager.GetString("Twos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string TwosShort {
            get {
                return ResourceManager.GetString("TwosShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for new game.
        /// </summary>
        internal static string WaitForGameLabel {
            get {
                return ResourceManager.GetString("WaitForGameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for players.
        /// </summary>
        internal static string WaitForPlayersLabel {
            get {
                return ResourceManager.GetString("WaitForPlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to won.
        /// </summary>
        internal static string WinLabel {
            get {
                return ResourceManager.GetString("WinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong name or password.
        /// </summary>
        internal static string WrongNamePassLabel {
            get {
                return ResourceManager.GetString("WrongNamePassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, sure!.
        /// </summary>
        internal static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
