//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanet.MagicalYatzy.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Sanet.MagicalYatzy.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AboutCaptionText {
            get {
                return ResourceManager.GetString("AboutCaptionText", resourceCulture);
            }
        }
        
        public static string AboutTextText {
            get {
                return ResourceManager.GetString("AboutTextText", resourceCulture);
            }
        }
        
        public static string OnlineLinkContent {
            get {
                return ResourceManager.GetString("OnlineLinkContent", resourceCulture);
            }
        }
        
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        public static string CloseButtonContent {
            get {
                return ResourceManager.GetString("CloseButtonContent", resourceCulture);
            }
        }
        
        public static string DevelopedByText {
            get {
                return ResourceManager.GetString("DevelopedByText", resourceCulture);
            }
        }
        
        public static string SpeedFastText {
            get {
                return ResourceManager.GetString("SpeedFastText", resourceCulture);
            }
        }
        
        public static string FullHouse {
            get {
                return ResourceManager.GetString("FullHouse", resourceCulture);
            }
        }
        
        public static string AngHighText {
            get {
                return ResourceManager.GetString("AngHighText", resourceCulture);
            }
        }
        
        public static string LargeStraight {
            get {
                return ResourceManager.GetString("LargeStraight", resourceCulture);
            }
        }
        
        public static string AngLowText {
            get {
                return ResourceManager.GetString("AngLowText", resourceCulture);
            }
        }
        
        public static string OfAKind {
            get {
                return ResourceManager.GetString("OfAKind", resourceCulture);
            }
        }
        
        public static string OnlineVersionText {
            get {
                return ResourceManager.GetString("OnlineVersionText", resourceCulture);
            }
        }
        
        public static string Pairs {
            get {
                return ResourceManager.GetString("Pairs", resourceCulture);
            }
        }
        
        public static string RateButtonContent {
            get {
                return ResourceManager.GetString("RateButtonContent", resourceCulture);
            }
        }
        
        public static string roll {
            get {
                return ResourceManager.GetString("roll", resourceCulture);
            }
        }
        
        public static string SpeedSlowText {
            get {
                return ResourceManager.GetString("SpeedSlowText", resourceCulture);
            }
        }
        
        public static string SmallStraight {
            get {
                return ResourceManager.GetString("SmallStraight", resourceCulture);
            }
        }
        
        public static string SupportText {
            get {
                return ResourceManager.GetString("SupportText", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string SpeedVeryFastText {
            get {
                return ResourceManager.GetString("SpeedVeryFastText", resourceCulture);
            }
        }
        
        public static string AngVeryHighText {
            get {
                return ResourceManager.GetString("AngVeryHighText", resourceCulture);
            }
        }
        
        public static string SpeedVerySlowText {
            get {
                return ResourceManager.GetString("SpeedVerySlowText", resourceCulture);
            }
        }
        
        public static string SettingsAngleCaptionText {
            get {
                return ResourceManager.GetString("SettingsAngleCaptionText", resourceCulture);
            }
        }
        
        public static string SettingsCaptionText {
            get {
                return ResourceManager.GetString("SettingsCaptionText", resourceCulture);
            }
        }
        
        public static string SettingsNumbersCaptionText {
            get {
                return ResourceManager.GetString("SettingsNumbersCaptionText", resourceCulture);
            }
        }
        
        public static string SettingsSpeedCaptionText {
            get {
                return ResourceManager.GetString("SettingsSpeedCaptionText", resourceCulture);
            }
        }
        
        public static string SettingsStyleCaptionText {
            get {
                return ResourceManager.GetString("SettingsStyleCaptionText", resourceCulture);
            }
        }
        
        public static string OtherAllWriteContent {
            get {
                return ResourceManager.GetString("OtherAllWriteContent", resourceCulture);
            }
        }
        
        public static string OtherSoftText {
            get {
                return ResourceManager.GetString("OtherSoftText", resourceCulture);
            }
        }
        
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        public static string AboutAction {
            get {
                return ResourceManager.GetString("AboutAction", resourceCulture);
            }
        }
        
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        public static string LeaderboardAction {
            get {
                return ResourceManager.GetString("LeaderboardAction", resourceCulture);
            }
        }
        
        public static string LeaderboardDescription {
            get {
                return ResourceManager.GetString("LeaderboardDescription", resourceCulture);
            }
        }
        
        public static string NetworkGameNotReadyMessage {
            get {
                return ResourceManager.GetString("NetworkGameNotReadyMessage", resourceCulture);
            }
        }
        
        public static string NewLocalGameAction {
            get {
                return ResourceManager.GetString("NewLocalGameAction", resourceCulture);
            }
        }
        
        public static string NewLocalGameDescription {
            get {
                return ResourceManager.GetString("NewLocalGameDescription", resourceCulture);
            }
        }
        
        public static string NewOnlineGameAction {
            get {
                return ResourceManager.GetString("NewOnlineGameAction", resourceCulture);
            }
        }
        
        public static string NewOnlineGameDescription {
            get {
                return ResourceManager.GetString("NewOnlineGameDescription", resourceCulture);
            }
        }
        
        public static string SettingsAction {
            get {
                return ResourceManager.GetString("SettingsAction", resourceCulture);
            }
        }
        
        public static string SettingsDescription {
            get {
                return ResourceManager.GetString("SettingsDescription", resourceCulture);
            }
        }
        
        public static string StartNewGameMessage {
            get {
                return ResourceManager.GetString("StartNewGameMessage", resourceCulture);
            }
        }
        
        public static string PlayerNameLabel {
            get {
                return ResourceManager.GetString("PlayerNameLabel", resourceCulture);
            }
        }
        
        public static string PlayerPasswordLabel {
            get {
                return ResourceManager.GetString("PlayerPasswordLabel", resourceCulture);
            }
        }
        
        public static string PlayerTypeLabel {
            get {
                return ResourceManager.GetString("PlayerTypeLabel", resourceCulture);
            }
        }
        
        public static string PlayersLabel {
            get {
                return ResourceManager.GetString("PlayersLabel", resourceCulture);
            }
        }
        
        public static string AddBotLabel {
            get {
                return ResourceManager.GetString("AddBotLabel", resourceCulture);
            }
        }
        
        public static string AddPlayerLabel {
            get {
                return ResourceManager.GetString("AddPlayerLabel", resourceCulture);
            }
        }
        
        public static string PlayerNameDefault {
            get {
                return ResourceManager.GetString("PlayerNameDefault", resourceCulture);
            }
        }
        
        public static string BotNameDefault {
            get {
                return ResourceManager.GetString("BotNameDefault", resourceCulture);
            }
        }
        
        public static string PlayerBotLabelLocalized {
            get {
                return ResourceManager.GetString("PlayerBotLabelLocalized", resourceCulture);
            }
        }
        
        public static string PlayerHumanLabelLocalized {
            get {
                return ResourceManager.GetString("PlayerHumanLabelLocalized", resourceCulture);
            }
        }
        
        public static string PlayerRememberLabelLocalized {
            get {
                return ResourceManager.GetString("PlayerRememberLabelLocalized", resourceCulture);
            }
        }
        
        public static string RulesLabel {
            get {
                return ResourceManager.GetString("RulesLabel", resourceCulture);
            }
        }
        
        public static string krBaby {
            get {
                return ResourceManager.GetString("krBaby", resourceCulture);
            }
        }
        
        public static string krExtended {
            get {
                return ResourceManager.GetString("krExtended", resourceCulture);
            }
        }
        
        public static string krSimple {
            get {
                return ResourceManager.GetString("krSimple", resourceCulture);
            }
        }
        
        public static string krStandard {
            get {
                return ResourceManager.GetString("krStandard", resourceCulture);
            }
        }
        
        public static string StartGameButton {
            get {
                return ResourceManager.GetString("StartGameButton", resourceCulture);
            }
        }
        
        public static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        public static string BonusShort {
            get {
                return ResourceManager.GetString("BonusShort", resourceCulture);
            }
        }
        
        public static string Chance {
            get {
                return ResourceManager.GetString("Chance", resourceCulture);
            }
        }
        
        public static string Fives {
            get {
                return ResourceManager.GetString("Fives", resourceCulture);
            }
        }
        
        public static string FivesShort {
            get {
                return ResourceManager.GetString("FivesShort", resourceCulture);
            }
        }
        
        public static string FourOfAKind {
            get {
                return ResourceManager.GetString("FourOfAKind", resourceCulture);
            }
        }
        
        public static string FourOfAKindShort {
            get {
                return ResourceManager.GetString("FourOfAKindShort", resourceCulture);
            }
        }
        
        public static string Fours {
            get {
                return ResourceManager.GetString("Fours", resourceCulture);
            }
        }
        
        public static string FoursShort {
            get {
                return ResourceManager.GetString("FoursShort", resourceCulture);
            }
        }
        
        public static string FullHouseShort {
            get {
                return ResourceManager.GetString("FullHouseShort", resourceCulture);
            }
        }
        
        public static string Kniffel {
            get {
                return ResourceManager.GetString("Kniffel", resourceCulture);
            }
        }
        
        public static string KniffelShort {
            get {
                return ResourceManager.GetString("KniffelShort", resourceCulture);
            }
        }
        
        public static string krBabyShort {
            get {
                return ResourceManager.GetString("krBabyShort", resourceCulture);
            }
        }
        
        public static string krExtendedShort {
            get {
                return ResourceManager.GetString("krExtendedShort", resourceCulture);
            }
        }
        
        public static string krSimpleShort {
            get {
                return ResourceManager.GetString("krSimpleShort", resourceCulture);
            }
        }
        
        public static string krStandardShort {
            get {
                return ResourceManager.GetString("krStandardShort", resourceCulture);
            }
        }
        
        public static string LargeStraightShort {
            get {
                return ResourceManager.GetString("LargeStraightShort", resourceCulture);
            }
        }
        
        public static string Ones {
            get {
                return ResourceManager.GetString("Ones", resourceCulture);
            }
        }
        
        public static string OnesShort {
            get {
                return ResourceManager.GetString("OnesShort", resourceCulture);
            }
        }
        
        public static string Sixs {
            get {
                return ResourceManager.GetString("Sixs", resourceCulture);
            }
        }
        
        public static string SixsShort {
            get {
                return ResourceManager.GetString("SixsShort", resourceCulture);
            }
        }
        
        public static string SmallStraightShort {
            get {
                return ResourceManager.GetString("SmallStraightShort", resourceCulture);
            }
        }
        
        public static string ThreeOfAKind {
            get {
                return ResourceManager.GetString("ThreeOfAKind", resourceCulture);
            }
        }
        
        public static string ThreeOfAKindShort {
            get {
                return ResourceManager.GetString("ThreeOfAKindShort", resourceCulture);
            }
        }
        
        public static string Threes {
            get {
                return ResourceManager.GetString("Threes", resourceCulture);
            }
        }
        
        public static string ThreesShort {
            get {
                return ResourceManager.GetString("ThreesShort", resourceCulture);
            }
        }
        
        public static string TotalShort {
            get {
                return ResourceManager.GetString("TotalShort", resourceCulture);
            }
        }
        
        public static string Twos {
            get {
                return ResourceManager.GetString("Twos", resourceCulture);
            }
        }
        
        public static string TwosShort {
            get {
                return ResourceManager.GetString("TwosShort", resourceCulture);
            }
        }
        
        public static string MoveLabel {
            get {
                return ResourceManager.GetString("MoveLabel", resourceCulture);
            }
        }
        
        public static string AgainLabel {
            get {
                return ResourceManager.GetString("AgainLabel", resourceCulture);
            }
        }
        
        public static string GameFinishedLabel {
            get {
                return ResourceManager.GetString("GameFinishedLabel", resourceCulture);
            }
        }
        
        public static string SaveScoreLabel {
            get {
                return ResourceManager.GetString("SaveScoreLabel", resourceCulture);
            }
        }
        
        public static string WinLabel {
            get {
                return ResourceManager.GetString("WinLabel", resourceCulture);
            }
        }
        
        public static string AllRecordsLabel {
            get {
                return ResourceManager.GetString("AllRecordsLabel", resourceCulture);
            }
        }
        
        public static string PlayerBestScoreLabel {
            get {
                return ResourceManager.GetString("PlayerBestScoreLabel", resourceCulture);
            }
        }
        
        public static string PlayerGamesLabel {
            get {
                return ResourceManager.GetString("PlayerGamesLabel", resourceCulture);
            }
        }
        
        public static string PlayerTotalScoreLabel {
            get {
                return ResourceManager.GetString("PlayerTotalScoreLabel", resourceCulture);
            }
        }
        
        public static string AppNameLabel {
            get {
                return ResourceManager.GetString("AppNameLabel", resourceCulture);
            }
        }
        
        public static string OtherAppsLabel {
            get {
                return ResourceManager.GetString("OtherAppsLabel", resourceCulture);
            }
        }
        
        public static string RemoveAdAction {
            get {
                return ResourceManager.GetString("RemoveAdAction", resourceCulture);
            }
        }
        
        public static string ReviewAppAction {
            get {
                return ResourceManager.GetString("ReviewAppAction", resourceCulture);
            }
        }
        
        public static string SendFeedbackAction {
            get {
                return ResourceManager.GetString("SendFeedbackAction", resourceCulture);
            }
        }
        
        public static string AWDescription {
            get {
                return ResourceManager.GetString("AWDescription", resourceCulture);
            }
        }
        
        public static string LaterLabel {
            get {
                return ResourceManager.GetString("LaterLabel", resourceCulture);
            }
        }
        
        public static string NeverLabel {
            get {
                return ResourceManager.GetString("NeverLabel", resourceCulture);
            }
        }
        
        public static string NewsDescription {
            get {
                return ResourceManager.GetString("NewsDescription", resourceCulture);
            }
        }
        
        public static string Privacy1Text {
            get {
                return ResourceManager.GetString("Privacy1Text", resourceCulture);
            }
        }
        
        public static string Privacy2Text {
            get {
                return ResourceManager.GetString("Privacy2Text", resourceCulture);
            }
        }
        
        public static string PrivacyLabelText {
            get {
                return ResourceManager.GetString("PrivacyLabelText", resourceCulture);
            }
        }
        
        public static string ReviewReminder {
            get {
                return ResourceManager.GetString("ReviewReminder", resourceCulture);
            }
        }
        
        public static string ReviewReminderHeader {
            get {
                return ResourceManager.GetString("ReviewReminderHeader", resourceCulture);
            }
        }
        
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
        
        public static string DicePokerAdLine1 {
            get {
                return ResourceManager.GetString("DicePokerAdLine1", resourceCulture);
            }
        }
        
        public static string DicePokerAdLine2 {
            get {
                return ResourceManager.GetString("DicePokerAdLine2", resourceCulture);
            }
        }
        
        public static string DicePokerAdLine3 {
            get {
                return ResourceManager.GetString("DicePokerAdLine3", resourceCulture);
            }
        }
        
        public static string DicePokerAdLine4 {
            get {
                return ResourceManager.GetString("DicePokerAdLine4", resourceCulture);
            }
        }
        
        public static string DicePokerAdLine5 {
            get {
                return ResourceManager.GetString("DicePokerAdLine5", resourceCulture);
            }
        }
        
        public static string DicePokerAdLine6 {
            get {
                return ResourceManager.GetString("DicePokerAdLine6", resourceCulture);
            }
        }
        
        public static string DicePokerAdLine7 {
            get {
                return ResourceManager.GetString("DicePokerAdLine7", resourceCulture);
            }
        }
        
        public static string DicePokerAdLine8 {
            get {
                return ResourceManager.GetString("DicePokerAdLine8", resourceCulture);
            }
        }
        
        public static string BestLocalLabel {
            get {
                return ResourceManager.GetString("BestLocalLabel", resourceCulture);
            }
        }
        
        public static string DeletePlayerLabel {
            get {
                return ResourceManager.GetString("DeletePlayerLabel", resourceCulture);
            }
        }
        
        public static string NoInetMessage {
            get {
                return ResourceManager.GetString("NoInetMessage", resourceCulture);
            }
        }
        
        public static string BestLocalShort {
            get {
                return ResourceManager.GetString("BestLocalShort", resourceCulture);
            }
        }
        
        public static string BestWeekLabel {
            get {
                return ResourceManager.GetString("BestWeekLabel", resourceCulture);
            }
        }
        
        public static string krMagic {
            get {
                return ResourceManager.GetString("krMagic", resourceCulture);
            }
        }
        
        public static string krMagicShort {
            get {
                return ResourceManager.GetString("krMagicShort", resourceCulture);
            }
        }
        
        public static string MagicRollLabel {
            get {
                return ResourceManager.GetString("MagicRollLabel", resourceCulture);
            }
        }
        
        public static string ManualSetLabel {
            get {
                return ResourceManager.GetString("ManualSetLabel", resourceCulture);
            }
        }
        
        public static string ForthRollLabel {
            get {
                return ResourceManager.GetString("ForthRollLabel", resourceCulture);
            }
        }
        
        public static string SelectNewDiceValueMessage {
            get {
                return ResourceManager.GetString("SelectNewDiceValueMessage", resourceCulture);
            }
        }
        
        public static string SelectDiceToChangeMessage {
            get {
                return ResourceManager.GetString("SelectDiceToChangeMessage", resourceCulture);
            }
        }
        
        public static string BestDayLabel {
            get {
                return ResourceManager.GetString("BestDayLabel", resourceCulture);
            }
        }
        
        public static string ArtifactsLabel {
            get {
                return ResourceManager.GetString("ArtifactsLabel", resourceCulture);
            }
        }
        
        public static string ArtifactsBonusMessage {
            get {
                return ResourceManager.GetString("ArtifactsBonusMessage", resourceCulture);
            }
        }
        
        public static string MagicRoomLabel {
            get {
                return ResourceManager.GetString("MagicRoomLabel", resourceCulture);
            }
        }
        
        public static string ArtifactsForLabel {
            get {
                return ResourceManager.GetString("ArtifactsForLabel", resourceCulture);
            }
        }
        
        public static string Cost1Label {
            get {
                return ResourceManager.GetString("Cost1Label", resourceCulture);
            }
        }
        
        public static string Cost2Label {
            get {
                return ResourceManager.GetString("Cost2Label", resourceCulture);
            }
        }
        
        public static string Cost3Label {
            get {
                return ResourceManager.GetString("Cost3Label", resourceCulture);
            }
        }
        
        public static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        public static string FirstTimeBonusDescription {
            get {
                return ResourceManager.GetString("FirstTimeBonusDescription", resourceCulture);
            }
        }
        
        public static string FirstTimeBonusLabel {
            get {
                return ResourceManager.GetString("FirstTimeBonusLabel", resourceCulture);
            }
        }
        
        public static string HowGetLabel {
            get {
                return ResourceManager.GetString("HowGetLabel", resourceCulture);
            }
        }
        
        public static string HowToGetDescription {
            get {
                return ResourceManager.GetString("HowToGetDescription", resourceCulture);
            }
        }
        
        public static string MagicArtifactsDescription {
            get {
                return ResourceManager.GetString("MagicArtifactsDescription", resourceCulture);
            }
        }
        
        public static string MagicRollDescription {
            get {
                return ResourceManager.GetString("MagicRollDescription", resourceCulture);
            }
        }
        
        public static string ManualSetDescription {
            get {
                return ResourceManager.GetString("ManualSetDescription", resourceCulture);
            }
        }
        
        public static string Offer1Description {
            get {
                return ResourceManager.GetString("Offer1Description", resourceCulture);
            }
        }
        
        public static string Offer2Description {
            get {
                return ResourceManager.GetString("Offer2Description", resourceCulture);
            }
        }
        
        public static string Offer3Description {
            get {
                return ResourceManager.GetString("Offer3Description", resourceCulture);
            }
        }
        
        public static string PurchaseDescription {
            get {
                return ResourceManager.GetString("PurchaseDescription", resourceCulture);
            }
        }
        
        public static string PurchaseErrorMessage {
            get {
                return ResourceManager.GetString("PurchaseErrorMessage", resourceCulture);
            }
        }
        
        public static string PurchaseLabel {
            get {
                return ResourceManager.GetString("PurchaseLabel", resourceCulture);
            }
        }
        
        public static string PurchaseMiniDescription {
            get {
                return ResourceManager.GetString("PurchaseMiniDescription", resourceCulture);
            }
        }
        
        public static string PurchaseMiniLabel {
            get {
                return ResourceManager.GetString("PurchaseMiniLabel", resourceCulture);
            }
        }
        
        public static string RerollDescription {
            get {
                return ResourceManager.GetString("RerollDescription", resourceCulture);
            }
        }
        
        public static string ResultBonusDescription {
            get {
                return ResourceManager.GetString("ResultBonusDescription", resourceCulture);
            }
        }
        
        public static string ResultBonusLabel {
            get {
                return ResourceManager.GetString("ResultBonusLabel", resourceCulture);
            }
        }
        
        public static string ArtifactsWinBuyMessage {
            get {
                return ResourceManager.GetString("ArtifactsWinBuyMessage", resourceCulture);
            }
        }
        
        public static string ChangeNameLabel {
            get {
                return ResourceManager.GetString("ChangeNameLabel", resourceCulture);
            }
        }
        
        public static string ChangePasswordLabel {
            get {
                return ResourceManager.GetString("ChangePasswordLabel", resourceCulture);
            }
        }
        
        public static string CheckingLabel {
            get {
                return ResourceManager.GetString("CheckingLabel", resourceCulture);
            }
        }
        
        public static string NoInternetLabel {
            get {
                return ResourceManager.GetString("NoInternetLabel", resourceCulture);
            }
        }
        
        public static string WrongNamePassLabel {
            get {
                return ResourceManager.GetString("WrongNamePassLabel", resourceCulture);
            }
        }
        
        public static string ContinueLabel {
            get {
                return ResourceManager.GetString("ContinueLabel", resourceCulture);
            }
        }
        
        public static string MoreLabel {
            get {
                return ResourceManager.GetString("MoreLabel", resourceCulture);
            }
        }
        
        public static string NoArtifactsLabel {
            get {
                return ResourceManager.GetString("NoArtifactsLabel", resourceCulture);
            }
        }
        
        public static string NoArtifactsMessage {
            get {
                return ResourceManager.GetString("NoArtifactsMessage", resourceCulture);
            }
        }
        
        public static string RemoveAdLabel {
            get {
                return ResourceManager.GetString("RemoveAdLabel", resourceCulture);
            }
        }
        
        public static string TapToApplyLabel {
            get {
                return ResourceManager.GetString("TapToApplyLabel", resourceCulture);
            }
        }
        
        public static string TapToChangeLabel {
            get {
                return ResourceManager.GetString("TapToChangeLabel", resourceCulture);
            }
        }
        
        public static string SoundLabel {
            get {
                return ResourceManager.GetString("SoundLabel", resourceCulture);
            }
        }
        
        public static string OffContent {
            get {
                return ResourceManager.GetString("OffContent", resourceCulture);
            }
        }
        
        public static string OnContent {
            get {
                return ResourceManager.GetString("OnContent", resourceCulture);
            }
        }
        
        public static string ShareDescription {
            get {
                return ResourceManager.GetString("ShareDescription", resourceCulture);
            }
        }
        
        public static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        public static string OnlyUniqueCanBuyMessage {
            get {
                return ResourceManager.GetString("OnlyUniqueCanBuyMessage", resourceCulture);
            }
        }
        
        public static string PlayerNoPasswordLabel {
            get {
                return ResourceManager.GetString("PlayerNoPasswordLabel", resourceCulture);
            }
        }
        
        public static string ReadyLabel {
            get {
                return ResourceManager.GetString("ReadyLabel", resourceCulture);
            }
        }
        
        public static string WaitForGameLabel {
            get {
                return ResourceManager.GetString("WaitForGameLabel", resourceCulture);
            }
        }
        
        public static string WaitForPlayersLabel {
            get {
                return ResourceManager.GetString("WaitForPlayersLabel", resourceCulture);
            }
        }
        
        public static string ClientLabel {
            get {
                return ResourceManager.GetString("ClientLabel", resourceCulture);
            }
        }
        
        public static string ClientOutdatedLabel {
            get {
                return ResourceManager.GetString("ClientOutdatedLabel", resourceCulture);
            }
        }
        
        public static string ClientOutdatedMessage {
            get {
                return ResourceManager.GetString("ClientOutdatedMessage", resourceCulture);
            }
        }
        
        public static string ClientUpdatedLabel {
            get {
                return ResourceManager.GetString("ClientUpdatedLabel", resourceCulture);
            }
        }
        
        public static string ServerLabel {
            get {
                return ResourceManager.GetString("ServerLabel", resourceCulture);
            }
        }
        
        public static string ServerOfflineLabel {
            get {
                return ResourceManager.GetString("ServerOfflineLabel", resourceCulture);
            }
        }
        
        public static string ServerOfflineMessage {
            get {
                return ResourceManager.GetString("ServerOfflineMessage", resourceCulture);
            }
        }
        
        public static string ServerOnlineLabel {
            get {
                return ResourceManager.GetString("ServerOnlineLabel", resourceCulture);
            }
        }
        
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        public static string ServerMaintananceMessage {
            get {
                return ResourceManager.GetString("ServerMaintananceMessage", resourceCulture);
            }
        }
        
        public static string SendLabel {
            get {
                return ResourceManager.GetString("SendLabel", resourceCulture);
            }
        }
        
        public static string RandomLabel {
            get {
                return ResourceManager.GetString("RandomLabel", resourceCulture);
            }
        }
        
        public static string TablesLabel {
            get {
                return ResourceManager.GetString("TablesLabel", resourceCulture);
            }
        }
        
        public static string AlreadyInGameMessage {
            get {
                return ResourceManager.GetString("AlreadyInGameMessage", resourceCulture);
            }
        }
        
        public static string MetroStudioText {
            get {
                return ResourceManager.GetString("MetroStudioText", resourceCulture);
            }
        }
        
        public static string BuyLabel {
            get {
                return ResourceManager.GetString("BuyLabel", resourceCulture);
            }
        }
        
        public static string FacebookLabel {
            get {
                return ResourceManager.GetString("FacebookLabel", resourceCulture);
            }
        }
        
        public static string RateLabel {
            get {
                return ResourceManager.GetString("RateLabel", resourceCulture);
            }
        }
        
        public static string ShareLabel {
            get {
                return ResourceManager.GetString("ShareLabel", resourceCulture);
            }
        }
        
        public static string DiceDescription {
            get {
                return ResourceManager.GetString("DiceDescription", resourceCulture);
            }
        }
        
        public static string ForWin8Label {
            get {
                return ResourceManager.GetString("ForWin8Label", resourceCulture);
            }
        }
        
        public static string ForWPLabel {
            get {
                return ResourceManager.GetString("ForWPLabel", resourceCulture);
            }
        }
        
        public static string ShareMessage {
            get {
                return ResourceManager.GetString("ShareMessage", resourceCulture);
            }
        }
        
        public static string LocalLabel {
            get {
                return ResourceManager.GetString("LocalLabel", resourceCulture);
            }
        }
        
        public static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        public static string LogoutLabel {
            get {
                return ResourceManager.GetString("LogoutLabel", resourceCulture);
            }
        }
        
        public static string LoginToFBLabel {
            get {
                return ResourceManager.GetString("LoginToFBLabel", resourceCulture);
            }
        }
        
        public static string ChatPanelLabel {
            get {
                return ResourceManager.GetString("ChatPanelLabel", resourceCulture);
            }
        }
        
        public static string DiceBoardLabel {
            get {
                return ResourceManager.GetString("DiceBoardLabel", resourceCulture);
            }
        }
        
        public static string NoPurchasesMessage {
            get {
                return ResourceManager.GetString("NoPurchasesMessage", resourceCulture);
            }
        }
        
        public static string ResultsTableLabel {
            get {
                return ResourceManager.GetString("ResultsTableLabel", resourceCulture);
            }
        }
        
        public static string ExitConfirmMessage {
            get {
                return ResourceManager.GetString("ExitConfirmMessage", resourceCulture);
            }
        }
        
        public static string PlayerNoNameLabel {
            get {
                return ResourceManager.GetString("PlayerNoNameLabel", resourceCulture);
            }
        }
        
        public static string CantJoinMessage {
            get {
                return ResourceManager.GetString("CantJoinMessage", resourceCulture);
            }
        }
        
        public static string FBPage {
            get {
                return ResourceManager.GetString("FBPage", resourceCulture);
            }
        }
        
        public static string ShareApp {
            get {
                return ResourceManager.GetString("ShareApp", resourceCulture);
            }
        }
        
        public static string NoRegistration {
            get {
                return ResourceManager.GetString("NoRegistration", resourceCulture);
            }
        }
    }
}
