<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <RootNamespace>Sanet.MagicalYatzy.Avalonia.Desktop</RootNamespace>
    </PropertyGroup>
    
    <PropertyGroup>
        <PublishSingleFile>true</PublishSingleFile>
    </PropertyGroup>

    <PropertyGroup>
        <ApplicationManifest>.windows/app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="$(AvaloniaDevToolsVersion)" Condition="'$(Configuration)' == 'Debug'" />
        <PackageReference Include="Sanet.MVVM.DI.Avalonia" Version="1.7.1211" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MagicalYatzy.Avalonia\MagicalYatzy.Avalonia.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include=".windows\app.manifest" />
    </ItemGroup>
    
</Project>


