using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using Sanet.MagicalYatzy.Online.Commands;
using Sanet.Transport;

namespace Sanet.MagicalYatzy.Online;

/// <summary>
/// The sole JSON (de)serialization point between online DTOs and the transport's
/// <see cref="TransportMessage"/> contract. The message-type <-> CLR-type mapping is generated by
/// the <c>OnlineMessageRegistryGenerator</c> source generator, so a newly added message type is
/// registered automatically without a manual registration list.
/// </summary>
public sealed class CommandRegistry
{
    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        Converters = { new JsonStringEnumConverter() }
    };

    /// <summary>
    /// All registered message types, keyed by their transport discriminator (CLR class name).
    /// </summary>
    public IReadOnlyDictionary<string, Type> Types => OnlineMessageTypeRegistry.Types;

    /// <summary>
    /// Looks up the CLR type for a transport discriminator, or <c>null</c> when unknown.
    /// </summary>
    public Type? GetType(string messageType) => OnlineMessageTypeRegistry.GetMessageType(messageType);

    /// <summary>
    /// Looks up the transport discriminator for a CLR type, or <c>null</c> when unregistered.
    /// </summary>
    public string? GetName(Type type) => OnlineMessageTypeRegistry.GetMessageTypeName(type);

    /// <summary>
    /// Converts an online message to a transport message. The transport discriminator is the
    /// message's CLR class name; <see cref="OnlineMessage.MessageType"/> is not serialized into the
    /// payload.
    /// </summary>
    public TransportMessage ToTransportMessage(OnlineMessage message, Guid sourceId)
    {
        var payload = JsonSerializer.Serialize(message, message.GetType(), SerializerOptions);
        return new TransportMessage
        {
            MessageType = message.MessageType,
            SourceId = sourceId,
            Payload = payload,
            Timestamp = DateTime.UtcNow
        };
    }

    /// <summary>
    /// Deserializes a transport message back to an online message. Returns <c>null</c> (rather than
    /// throwing) for an unknown discriminator or an invalid payload.
    /// </summary>
    public OnlineMessage? TryDeserialize(TransportMessage message)
    {
        var type = GetType(message.MessageType);
        if (type == null)
        {
            return null;
        }

        try
        {
            return JsonSerializer.Deserialize(message.Payload, type, SerializerOptions) as OnlineMessage;
        }
        catch (JsonException)
        {
            return null;
        }
    }
}
