using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sanet.MagicalYatzy.Core.SourceGenerators;

/// <summary>
/// Generates <c>OnlineMessageTypeRegistry</c>, the message-type <-> CLR-type mapping for the online
/// protocol. Every concrete (non-abstract) subclass of <c>OnlineMessage</c> is registered
/// automatically, so a newly added message type needs no manual registration list.
/// </summary>
[Generator]
public sealed class OnlineMessageRegistryGenerator : IIncrementalGenerator
{
    private const string OnlineMessageMetadataName = "Sanet.MagicalYatzy.Online.Commands.OnlineMessage";
    private const string GeneratedHintName = "OnlineMessageTypeRegistry.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidateTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax { BaseList: not null },
                static (ctx, _) => GetDeclaredType(ctx))
            .Where(static symbol => symbol is not null)
            .Select(static (symbol, _) => symbol!);

        var compilationAndTypes = context.CompilationProvider.Combine(candidateTypes.Collect());

        context.RegisterSourceOutput(compilationAndTypes, static (spc, source) =>
            Execute(source.Left, source.Right, spc));
    }

    private static INamedTypeSymbol? GetDeclaredType(GeneratorSyntaxContext context)
    {
        var typeDeclaration = (TypeDeclarationSyntax)context.Node;
        return context.SemanticModel.GetDeclaredSymbol(typeDeclaration) as INamedTypeSymbol;
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> candidates,
        SourceProductionContext context)
    {
        try
        {
            var baseSymbol = compilation.GetTypeByMetadataName(OnlineMessageMetadataName);
            var source = baseSymbol is null
                ? GenerateEmptyRegistry()
                : GenerateRegistry(candidates.Where(c => IsConcreteDerived(c, baseSymbol)));

            context.AddSource(GeneratedHintName, SourceText.From(source, Encoding.UTF8));
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "OMRG001",
                    "Source generator error",
                    $"Error in OnlineMessageRegistryGenerator: {ex.Message}\nStack trace: {ex.StackTrace}",
                    "SourceGenerator",
                    DiagnosticSeverity.Error,
                    true),
                Location.None));
        }
    }

    private static bool IsConcreteDerived(INamedTypeSymbol type, INamedTypeSymbol baseSymbol)
    {
        if (type.IsAbstract)
        {
            return false;
        }

        for (INamedTypeSymbol? current = type.BaseType; current is not null; current = current.BaseType)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseSymbol))
            {
                return true;
            }
        }

        return false;
    }

    private static string GenerateRegistry(IEnumerable<INamedTypeSymbol> types)
    {
        var messageTypes = types.OrderBy(t => t.Name).ToList();
        var namespaces = messageTypes
            .Select(t => t.ContainingNamespace.ToDisplayString())
            .Distinct()
            .OrderBy(ns => ns);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace Sanet.MagicalYatzy.Online");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class OnlineMessageTypeRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        private static readonly Dictionary<string, Type> s_types = new();");
        sb.AppendLine("        private static readonly Dictionary<Type, string> s_names = new();");
        sb.AppendLine();
        sb.AppendLine("        static OnlineMessageTypeRegistry()");
        sb.AppendLine("        {");
        foreach (var type in messageTypes)
        {
            sb.AppendLine($"            Register(\"{type.Name}\", typeof({type.ToDisplayString()}));");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public static IReadOnlyDictionary<string, Type> Types => s_types;");
        sb.AppendLine();
        sb.AppendLine("        public static Type? GetMessageType(string messageType)");
        sb.AppendLine("        {");
        sb.AppendLine("            s_types.TryGetValue(messageType, out var type);");
        sb.AppendLine("            return type;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public static string? GetMessageTypeName(Type type)");
        sb.AppendLine("        {");
        sb.AppendLine("            s_names.TryGetValue(type, out var name);");
        sb.AppendLine("            return name;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static void Register(string name, Type type)");
        sb.AppendLine("        {");
        sb.AppendLine("            s_types[name] = type;");
        sb.AppendLine("            s_names[type] = name;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateEmptyRegistry()
    {
        return """
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Collections.Generic;

            namespace Sanet.MagicalYatzy.Online
            {
                internal static class OnlineMessageTypeRegistry
                {
                    public static IReadOnlyDictionary<string, Type> Types { get; } = new Dictionary<string, Type>();

                    public static Type? GetMessageType(string messageType) => null;

                    public static string? GetMessageTypeName(Type type) => null;
                }
            }
            """;
    }
}
