name: Build Mac App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      TEAM_ID: 'Z8GJWJ4Q4E'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json

      - name: Extract version from Directory.Build.props
        id: extract_version
        shell: bash
        run: |
          VERSION=$(grep -oP '(?<=<VersionPrefix>).*(?=</VersionPrefix>)' Directory.Build.props)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version extracted: $VERSION"

      - name: Setup Keychain
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          DEV_ID_CERT: ${{ secrets.DEV_ID_CERT }}
          DEV_ID_INSTALLER_CERT: ${{ secrets.DEV_ID_INSTALLER_CERT }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          NOTARY_TOOL_PASSWORD: ${{ secrets.NOTARY_TOOL_PASSWORD }}
        run:
          sh src/Avalonia/MagicalYatzy.Avalonia.Desktop/.macos/prepare_ci_cert.sh

      - name: Build and publish
        run: |
          cd src/Avalonia/MagicalYatzy.Avalonia.Desktop
          sh .macos/make-app.sh

      - name: Sign
        run: |
          cd src/Avalonia/MagicalYatzy.Avalonia.Desktop
          sh .macos/sign-app.sh

      - name: Package
        env:
          INSTALLER_PLIST: '.macos/Installer.plist'
          PACKAGE_ROOT: 'bin/app'
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          cd src/Avalonia/MagicalYatzy.Avalonia.Desktop
          cp $INSTALLER_PLIST $PACKAGE_ROOT/Installer.plist
          cd $PACKAGE_ROOT
          pkgbuild --root . \
                   --component-plist Installer.plist \
                   --sign "Developer ID Installer: Anton Makarevich (Z8GJWJ4Q4E)" \
                   --filter .DS_Store \
                   --filter *.pkg \
                   --install-location /Applications MagicalYatzy.pkg

      - name: Notarise app
        run: |
          cd src/Avalonia/MagicalYatzy.Avalonia.Desktop/bin/app
          xcrun notarytool submit "MagicalYatzy.pkg" --wait --keychain-profile "AC_PASSWORD"
          xcrun stapler staple "MagicalYatzy.pkg"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src/Avalonia/MagicalYatzy.Avalonia.Desktop/bin/app/MagicalYatzy.pkg
          draft: false
          prerelease: false
          generate_release_notes: false

      - name: Upload Installer as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MagicalYatzy-Mac-${{ env.APP_VERSION }}
          path: src/Avalonia/MagicalYatzy.Avalonia.Desktop/bin/app/MagicalYatzy.pkg
          retention-days: 90

      - name: Clean up keychain
        if: ${{ always() }}
        run: security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
