name: Publish Windows App

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Restore dependencies
        run: |
          dotnet restore MagicalYatzyAUI/MagicalYatzyAUI.Desktop/MagicalYatzyAUI.Desktop.csproj

      - name: Build and publish
        run: dotnet publish MagicalYatzyAUI/MagicalYatzyAUI.Desktop/MagicalYatzyAUI.Desktop.csproj -c Release -o ./publish

      - name: Get branch name
        id: branch_name
        run: |
          echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Replace slashes with underscores
        run: |
          sanitized_branch_name=$(echo "${{ env.branch_name }}" | tr '/' '_')
          echo "sanitized_branch_name=$sanitized_branch_name" >> $GITHUB_ENV

      - name: Archive to ZIP
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'mg-win_${{ steps.sanitized_branch_name.outputs.sanitized_branch_name }}.zip'

        
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: magical-yatzy_windows
          path: mg-win_*.zip