name: Publish WASM app

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build configuration (Release or Debug)'
        required: true
        default: 'Release'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    
    steps:
      - name: Inject extra env vars
        uses: FranzDiebold/github-env-vars-action@v2.4.0

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: |
          cd src/Avalonia/MagicalYatzy.Avalonia.Browser
          dotnet workload restore
          dotnet workload repair
          dotnet publish -c ${{ github.event.inputs.configuration || 'Release' }}

      - name: Deploy the website
        uses: tibor19/static-website-deploy@v4
        with:
          enabled-static-website: 'true'
          folder: src/Avalonia/MagicalYatzy.Avalonia.Browser/bin/${{ github.event.inputs.configuration || 'Release' }}/net9.0-browser/publish/wwwroot
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION }}
