name: Build SPA

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Inject extra env vars
        uses: FranzDiebold/github-env-vars-action@v2

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Restore workloads
        run: |
          cd MagicalYatzyAUI/MagicalYatzyAUI.Browser
          dotnet workload restore
          dotnet workload repair
          dotnet publish -c Release

      - name: Deploy the website
        uses: tibor19/static-website-deploy@v2
        with:
          enabled-static-website: 'true'
          folder: 'MagicalYatzyAUI/MagicalYatzyAUI.Browser/bin/Release/net7.0/browser-wasm/publish'
          connection-string: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_FIELD_08785C503 }}
#      - name: Build And Deploy
#        id: builddeploy
#        uses: Azure/static-web-apps-deploy@v1
#        with:
#          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_FIELD_08785C503 }}
#          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
#          action: "upload"
#          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
#          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
#          app_location: "MagicalYatzyAUI/MagicalYatzyAUI.Browser" # App source code path
#          api_location: "" # Api source code path - optional
#          output_location: "MagicalYatzyAUI/MagicalYatzyAUI.Browser/bin/Release/net7.0/browser-wasm/publish" # Built app content directory - optional
#          ###### End of Repository/Build Configurations ######
