name: Publish Linux App

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Inject extra env vars
        uses: FranzDiebold/github-env-vars-action@v2.4.0
        
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Build and publish
        run: |
          dotnet publish src/Avalonia/MagicalYatzy.Avalonia.Desktop/MagicalYatzy.Avalonia.Desktop.csproj -c Release  -r linux-x64 -o src/Avalonia/MagicalYatzy.Avalonia.Desktop/bin/Release/ubuntu/publish --self-contained

      - name: Archive
        run: |
          cd src/Avalonia/MagicalYatzy.Avalonia.Desktop/bin/Release/ubuntu/publish
          rm *.pdb
          chmod 777 MagicalYatzy.Avalonia.Desktop
          zip -r MagicalYatzy.zip .

      - name: Upload to App Center
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APP_CENTER_TOKEN }}
        run: |
          npm install -g appcenter-cli
          appcenter distribute groups publish -f src/Avalonia/MagicalYatzy.Avalonia.Desktop/bin/Release/ubuntu/publish/MagicalYatzy.zip -g Alpha --app anton.makarevich/Magical-Yatzy-Linux --build-version 0.1 --build-number ${{ github.run_number }}