name: Publish Mac App

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Inject extra env vars
        uses: FranzDiebold/github-env-vars-action@v2
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Restore dependencies
        run: |
          dotnet restore MagicalYatzyAUI/MagicalYatzyAUI.Desktop/MagicalYatzyAUI.Desktop.csproj

      - name: Build and publish
        run: |
          dotnet publish MagicalYatzyAUI/MagicalYatzyAUI.Desktop/MagicalYatzyAUI.Desktop.csproj -r osx-x64 -p:UseAppHost=true -c Release -o ./publish

      - name: Archive to ZIP
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: './publish'
          filename: 'mg-mac_$CI_REF_NAME_SLUG.zip'

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: magical-yatzy_macos
          path: mg-mac_*.zip