name: Build and Test
on:
  push:
    branches:
      - develop
  pull_request:

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Run DTO tests
        run: dotnet test tests/MagicalYatzy.Dto.Tests/MagicalYatzy.Dto.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute=GeneratedCodeAttribute /p:Include=[MagicalYatzy]*

      - name: Upload DTO tests results
        run: bash <(curl -s https://codecov.io/bash) -f "tests/MagicalYatzy.Dto.Tests/coverage.opencover.xml" -t ${{ secrets.CODECOV_TOKEN }}

      - name: Run Core tests
        run: dotnet test tests/MagicalYatzy.Core.Tests/MagicalYatzy.Core.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute=GeneratedCodeAttribute /p:Include=[MagicalYatzy]*

      - name: Upload Core tests results
        run: bash <(curl -s https://codecov.io/bash) -f "tests/MagicalYatzy.Core.Tests/coverage.opencover.xml" -t ${{ secrets.CODECOV_TOKEN }}
